workflows:
  ios_secure_files:
    name: iOS Build mit Secure Files (empfohlen)
    environment:
      # Binde deine Secure-Files-Gruppe ein (vorher in Codemagic anlegen):
      groups:
        - ios_credentials   # enthält: CM_CERTIFICATE (File), CM_CERTIFICATE_PASSWORD (Secure String), CM_PROVISIONING_PROFILE (File)
      vars:
        WORKSPACE: "App.xcworkspace"   # falls .xcodeproj: leer lassen oder unten Pfad automatisch ermitteln
        SCHEME: "App"
        EXPORT_METHOD: "app-store"     # app-store | development | ad-hoc | enterprise

    scripts:
      - name: Preflight
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          [[ -f "${CM_CERTIFICATE:-}" ]] || { echo "FEHLT: CM_CERTIFICATE (File-Variable)"; exit 1; }
          [[ -f "${CM_PROVISIONING_PROFILE:-}" ]] || { echo "FEHLT: CM_PROVISIONING_PROFILE (File-Variable)"; exit 1; }
          [[ -n "${CM_CERTIFICATE_PASSWORD:-}" ]] || { echo "FEHLT: CM_CERTIFICATE_PASSWORD (Secure String)"; exit 1; }
          echo "Workspace='${WORKSPACE:-}'  Scheme='${SCHEME:-}'  Export='${EXPORT_METHOD:-}'"

      - name: Install signing
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          keychain initialize
          keychain add-certificates \
            --certificate "$CM_CERTIFICATE" \
            --certificate-password "$CM_CERTIFICATE_PASSWORD"
          xcode-project use-profiles \
            --provisioning-profile "$CM_PROVISIONING_PROFILE"

      - name: Build IPA
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          DEST="-destination 'generic/platform=iOS'"
          if [[ -n "${WORKSPACE:-}" && -f "$WORKSPACE" ]]; then
            xcode-project build-ipa \
              --workspace "$WORKSPACE" \
              --scheme "$SCHEME" \
              --archive-flags="$DEST" \
              --export-method "$EXPORT_METHOD"
          else
            PROJ="${WORKSPACE%.xcworkspace}.xcodeproj"
            [[ -f "$PROJ" ]] || PROJ="$(ls *.xcodeproj | head -n1)"
            xcode-project build-ipa \
              --project "$PROJ" \
              --scheme "$SCHEME" \
              --archive-flags="$DEST" \
              --export-method "$EXPORT_METHOD"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/Archives/**/*
