workflows:
  ios_inline_signing:
    name: iOS Inline Signing (nur Workflow)
    environment:
      vars:
        SCHEME: "App"
        EXPORT_METHOD: "app-store"
        P12_BASE64: "MIINGgIBAzCCDMgGCSqGSIb3DQEHAaCCDLkEggy1MIIMsTCCBuoGCSqGSIb3DQEHBqCCBtswggbXAgEAMIIG0AYJKoZIhvcNAQcBMF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBAdL1LKBpFSFOoFjkqIEDU7AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ6VZan2d5s5FcLkHKL9+55oCCBmAhTYG3xU19ISegrMlGJ9NfSHeLHKRy+z5cdNBOG0V9l0OZJfYCQf8AZlOZaUOxJX3k+o3l8t09+RZIhWHbklN3lKZjVCejRfDG2a1pieWH0D9Icp4/dCJgGdcTHpWQBX1cTOunLpcOHlKZ1FPCk6UsNYrOfTtzOyR6gOZzNPzrRv3WjQsgYuLSV9Oyz9/M2Aqul/R3O/G4AHQ/mVpl2nmKCDROpmoya2P3tNodsH/dYF2rS4s+mpVh1Cxhfqjo6r7CtMB/x7fKeB0vcIBxqTGmfyZPIMuCAcPEdR2uX501OtIF+jexZmlJbvol9PpuZH9yk3CUg1wm6+YP55RVStcZQdoSuUFBk4VFMnuonMBZp7CvFkJCS6yAwNB+fynFMOXYeD7Vx9lqXHr1w0ggII3VLp0jZDId42Ffm9QS7Pqx8x0g0RnGRZKXXbBJSVrtiAI6/AGZxKDwZJf/RYQsSZGMcFnni3qWPhtGBpyyb1+caY6dyMORCZY5FymsA1H5ggOIeUOkZfwyV8kkMvWNYtne8EGPZnvAhjuC+x8GfLudVryTz2mobZcCS7OcFbVZGoCXl7CTzAouAKUzhW6RGWO3HZMStHjrTjiX5dphbYZDQX6fOwjaBROjxkubHkh1Vy/KxNJ3ydJenJdkcoBSJec2fgMM0+puTD6hY0FqoUKWsO7J0KKLBQB3m62ru4DdOOtUh+S31nfo1SqClXHiHrtqXV8XOGFV0yqARV842Sqg6ZslWxtvxSRu8H6KTMdZ7VKhQyH9Mx23AU7uvxg1wRboa+QgGTFrGO6aIjbVzvC/IuqrYGmQMdFSDkIavTPsFSdJOfp/yhpr8NxFoz2iBU/vyWRJCULw4vH2iCEXq3wBp9YlxjIrfnJekf++BzFoTYkgdtQ1PduKB8r5GjOokTQWKXD3koNAoSurDctrSaIOyXasXqmMe4FmcCSoQSwUoC5w+r981FXfMaHAWqhjM+4/HPRN3yPzM5oI3Ffz9q58I5IG1oKdar7nuAF4ifSdR9GWixkPaW2Wb5xRKGiGKzd/S48MyvmPO2asCy39tt+HJUFM18uqlwVUCB+EOKMQYOe/+bjpIkIs9KOQxp/mKONX8ktaQ9v6gci+GXY77RuKe8Aszhlw3n+/LmtJVWyTPN0O6fYk87EMHoJY7jpNPsSxpi+Q/e5UWSa7seUgPhWKA2/bBAE2MRqM78KGgUQRbCNopJnQ8BWETx5G6q8m12uMFZnYX7gmEhT5q0+gn9Wx1mBYYk0rtgdEQpunUNn5KxwmzH6Km/w6j5ko1I3V0ul3+HTFlrfUFTf4HIZ1nUs1+/G24eZQY3COG4AKuTKUuQl0Rbdwt4sk+cJSlVdsxkfcV0BX1e6ZbZfmgLdcPu9+lByIcGT462rbSqoveVueSLZrRsIWEwPnMcx8zPUKCL3T4MqhVqGszWlI3OhJMNmttxNHuOnJSQwjGaEPYuEdYBoYQrW4iHx1SVHFJ6g05RIiZVSJNAQwiLVX+NXfrN5JQsgnBaxcu3ViDOa02StsOXph+yLHEEyfbaPKcwnzcFV8P0ZHu4/DXySDXBGf7MBFaYApHyk/rl68oYCQJ4iJOxFNrh29p4tdTWIQzicaZtVHrTuFHSIrzlzRbB/m/54GNIMqJCXI8QskhrMkPLjvRbqFAJDB9+J1v3F2ZE1RPfcljR6B24noW3WoyYl38Vzq34xJtIBcYub3e+6DHNTwX5LseBEaQz6DzPcLC2KccSJpJIKOHSF4A223eSTYReKSQWNKYuwckpfWeMKZswbn6TYfSGJno59bXAq1kaDWVgjGN0sYGhj0ZslxHH6KTIiK++nIy0OG980/agdsjGhopBfinP+yfg6k9cYpqhtSFPfnAe4ODNZS4j9pMRWLuTjOA045yX4w5v4ySzFHHPIJpoQZ5OGeBPGeszJbXvtyABxgH5wjOqMn5MEoO/G7pDRCqiALBhTQacVWFm6OIuAbeYA6xrHTjCV0Lt0Slw4vsCi5EdD5LcZHjwTZzK5LxsH1cpYUdqQJ0VcAKZzCTRQBGuXeAor0DHh93FQ7+kfFRQPCCBpuPchjQ2WbXPZ8NkiBSuv9TJP8AhtXaDBS1wXB54C1AVCTFRQgx7SGUrlav5YUKhDk1O5nezrbRwt/PebxOrc6AAdC+ZaXlQ9h2Va//k8wggW/BgkqhkiG9w0BBwGgggWwBIIFrDCCBagwggWkBgsqhkiG9w0BDAoBAqCCBTkwggU1MF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBDQSQXrUXhjOYjATYshh5P7AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQGmd4OUt1W+zZntQ2dDS4VwSCBNDnvTPYiAx9YcH/zQeW/K8IL0pRkJH5MFGDJ+sz5dOib66IO9Amw/cvAaLZ/YGpmRBEkSBENIi4EAYdZrtpyHVMonqG9x1qX6qF7hPg8QiNmcObBjacu0tsZDzxJRngqQaKOtl39WMBHTW15unPXRYnEYl6tSU3x7XSzHZ4NJ7p5R89o0pMIRpaSZHXbfrONCdQIbDiQwSSyGTZ42RAk20TVTH7V+ONsqPHOee17NdPxBEOsPaDwUY0NQkHEk+2MSbqmjd3cUXdoZXieyvjjj/ueXRzFnGcyCSCXEMT6U1p1vqhBAOa1/BPboGEX2kRMkPYuOoPmoDiA/Yrx+U0KF1iq3J9GgikHrGvRAnvyfgIW7Q8AguoriDQ1l5UPWdq2KWRk3HxGNBrRKtSqufq2fvYdqVN+ztysuQEWevDN7aaycdogK4zSoooWq6cw7L1kVWCvkO3EvZvkd5Kkff7807ZKqJQpNlan1AIsI6K+WLyi/yPE0u0PfFIO8lfojmuX8I9ahKDV5Y3Po3Pl1QpeeTXK76ZUMIvX/fDEAu4BGY1zgJ8Onuo5Ob6QasK7pF98dmAKpDfe4c9qRw/A3LgrDfNnmIfiLvFR84JkzwvGZxlkec51trygFJDt7SRwejMa9uzV2DIsdfvMkecPNLbsHJ4WIKPeduzPKJZyxOe/N4a9doX92ixzUGit/keYZr4Tb18URRPYbYOZixQUemEdDq03rMbM5PmDNIX0TLp03FbogwAaAXI5gO5DwQ+4YDGKpVlXesR57Imk3tcfWVttStRcDskCweVTeB5STkL7RBr6fzroxoYLe7C3B8GvDAfC5uWr7LFalxMd1s0bksrVFMamHEaOGb4w8M7K/e8aOYb6CHZUW0fj5g0HqUcOvP9Wf215pLRCtue7lwECS1939pEYv/64ejfR69ItXK0qm5A9BNhKDquYL1wFm5ddnPtxkFtaP8q4vpNlvKn4G0sl3o4kbd0VI+N5p8AYnEj0j9AZcOycctShYu11AtmUFK1hui3+kLkSZbz1M1Ub7/yJomIUSKxXwTxyrE9eM51EN5geWyGv2ZQ4Atd6HWlZTnAVHXCnHrXqrL14zDXSCh5xPC8DB3NB7RHjWmO6jf4IL+Op2zF7GhqOns42zJOuBDvMq7+XFIH9IHIwkgpohalGIlWrly+M2N+jtgCkj7gkUQlg/2C/YydrnLq9B8hWlrOytIizzAaQJz2uY4fitWnK8Ma7XMP/PyvjDq+9jDON52ECXJhfvEZ2J4RaxlET/HLP6NFxllbZX+CbkptNgFqbSCLIAuFJtN4swmmfc3I7pkZCHtYZt7JNOBZPtV6AcR8bnXv73kvOE4SdwcEUrL7rNSVTcnPpi8ywScT6J+rvS9JAJeViiFj49vefRF0VN9KlG/SqQP/04O6gl8NqlHMRcseoC4ivCXmlcKq/h1EWNwMc2z02JB+tXnuSU6eRykSqAznjYbxEFmIvoI1FZ2FYTPiS8P2LJCX+MCNZ0aJzUhRgqTssZG9EUwcX6VToSKTaRW1j82iPprni2lczcm6TjJWH81OQczQqcVYgHtaiD29gPpqGXc8ULrpcvtSop6lkdcMOjxPsMRqOeHhMDz1XDHaN3tifdVnXY5H96avdMdN/DFYMCMGCSqGSIb3DQEJFTEWBBSI9sO5FWCMYWfLfyxQB7eUZwqQ8zAxBgkqhkiG9w0BCRQxJB4iAFAAYQByAHQAeQBQAGkAbgBTAGkAZwBuAGEAdAB1AHIAZTBJMDEwDQYJYIZIAWUDBAIBBQAEIBVsIffB93ng+h5nbeyrXFyo3pIzErauD+kM0U6P9aCtBBBUAlQ0znxosKMKADrUdminAgIIAA=="
        MOBILEPROVISION_BASE64: "MII2WgYJKoZIhvcNAQcCoII2SzCCNkcCAQExCzAJBgUrDgMCGgUAMIImZwYJKoZIhvcNAQcBoIImWASCJlQ8P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCI/Pgo8IURPQ1RZUEUgcGxpc3QgUFVCTElDICItLy9BcHBsZS8vRFREIFBMSVNUIDEuMC8vRU4iICJodHRwOi8vd3d3LmFwcGxlLmNvbS9EVERzL1Byb3BlcnR5TGlzdC0xLjAuZHRkIj4KPHBsaXN0IHZlcnNpb249IjEuMCI+Ci..."
        P12_PASSWORD: "Yamahayz85"

    scripts:
      - name: Install signing (inline)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          require() { [[ -n "${!1:-}" ]] || { echo "$1 leer"; exit 1; }; }
          require P12_BASE64
          require MOBILEPROVISION_BASE64
          require P12_PASSWORD

          mkdir -p /tmp/signing

          # P12 strikt Base64
          python3 - <<'PY'
          import os, base64, pathlib, re, sys, binascii
          def clean_b64_strict(label: str, s: str) -> bytes:
              t = ''.join(s.split()).strip('"').strip("'")
              if not re.fullmatch(r'[A-Za-z0-9+/=]+', t or ""):
                  print(f"{label}: Kein gültiges Base64", file=sys.stderr); sys.exit(2)
              t += "=" * ((4 - len(t) % 4) % 4)
              try:
                  return base64.b64decode(t, validate=True)
              except binascii.Error:
                  print(f"{label}: Base64-Decode fehlgeschlagen", file=sys.stderr); sys.exit(2)
          pathlib.Path("/tmp/signing/cert.p12").write_bytes(
              clean_b64_strict("P12_BASE64", os.environ["P12_BASE64"])
          )
          PY

          # Mobileprovision: Base64 CMS **oder** rohe/BASE64-Plist akzeptieren
          python3 - <<'PY'
          import os, base64, pathlib, re, sys, binascii
          raw = os.environ["MOBILEPROVISION_BASE64"]
          s = ''.join(raw.split()).strip('"').strip("'")
          data = None
          # Versuche striktes Base64
          if re.fullmatch(r'[A-Za-z0-9+/=]+', s or ""):
              s += "=" * ((4 - len(s) % 4) % 4)
              try:
                  data = base64.b64decode(s, validate=True)
              except binascii.Error:
                  data = None
          # Fallback: roher Inhalt
          if data is None:
              data = raw.encode("utf-8")
          pathlib.Path("/tmp/signing/profile.mobileprovision").write_bytes(data)
          PY

          /usr/bin/openssl pkcs12 -info -in /tmp/signing/cert.p12 -passin pass:"$P12_PASSWORD" -nodes -nokeys >/dev/null \
            || { echo "Ungültiges .p12 oder falsches Passwort"; exit 1; }

          keychain initialize
          keychain add-certificates --certificate /tmp/signing/cert.p12 --certificate-password "$P12_PASSWORD"

          PROV="/tmp/signing/profile.mobileprovision"
          [[ -s "$PROV" ]] || { echo "Provisioning-Profile leer"; exit 1; }

          PLIST="/tmp/signing/profile.plist"
          # 1) Versuche CMS zu decodieren
          if /usr/bin/security cms -D -i "$PROV" -o "$PLIST" >/dev/null 2>&1; then
            :
          else
            # 2) Wenn schon Plist, kopieren und in XML konvertieren
            cp "$PROV" "$PLIST"
            if ! /usr/bin/plutil -convert xml1 "$PLIST" >/dev/null 2>&1; then
              echo "Provisioning-Profile ungültig: weder CMS noch valide Plist"; exit 1
            fi
          fi

          # UUID extrahieren
          UUID="$(/usr/bin/plutil -extract UUID raw -o - "$PLIST" 2>/dev/null || true)"
          if [[ -z "$UUID" ]]; then
            UUID="$(/usr/libexec/PlistBuddy -c 'Print :UUID' "$PLIST" 2>/dev/null || true)"
          fi
          [[ -n "$UUID" ]] || { echo "Profil ungültig: UUID nicht gefunden"; exit 1; }

          DST_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$DST_DIR"
          cp "$PROV" "$DST_DIR/$UUID.mobileprovision"

          xcode-project use-profiles

      - name: Build IPA
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          # iOS-Workspace/Projekt suchen. macOS ausschließen.
          WS="$(find ios -maxdepth 3 -name "*.xcworkspace" -print -quit 2>/dev/null || true)"
          if [[ -z "${WS}" ]]; then
            WS="$(find . -path "./macos" -prune -o -name "*.xcworkspace" -print -quit || true)"
          fi

          PROJ=""
          if [[ -z "${WS}" ]]; then
            PROJ="$(find ios -maxdepth 3 -name "*.xcodeproj" -print -quit 2>/dev/null || true)"
            if [[ -z "${PROJ}" ]]; then
              PROJ="$(find . -path "./macos" -prune -o -name "*.xcodeproj" -print -quit || true)"
            fi
          fi
          [[ -n "${WS}" || -n "${PROJ}" ]] || { echo "Kein iOS .xcworkspace oder .xcodeproj gefunden"; exit 1; }

          # Scheme automatisch ermitteln, wenn nicht gesetzt
          if [[ -z "${SCHEME:-}" ]]; then
            if [[ -n "${WS}" ]]; then
              SCHEME="$(
                /usr/bin/xcodebuild -workspace "${WS}" -list -json \
                | /usr/bin/python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("workspace",{}).get("schemes",[":none:"])[0])'
              )"
            else
              SCHEME="$(
                /usr/bin/xcodebuild -project "${PROJ}" -list -json \
                | /usr/bin/python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("project",{}).get("schemes",[":none:"])[0])'
              )"
            fi
          fi
          [[ -n "${SCHEME}" && "${SCHEME}" != ":none:" ]] || { echo "Konnte Scheme nicht ermitteln. Setze SCHEME explizit."; exit 1; }

          # ExportOptions statt --export-method
          EXPORT_METHOD="${EXPORT_METHOD:-app-store}"
          EXPORT_PLIST="/tmp/ExportOptions.plist"
          cat > "${EXPORT_PLIST}" <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>${EXPORT_METHOD}</string>
            <key>signingStyle</key><string>manual</string>
            <key>destination</key><string>export</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>uploadBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          # Zielplattform
          ARCHIVE_FLAGS="-destination 'generic/platform=iOS'"

          if [[ -n "${WS}" ]]; then
            echo "Using workspace: ${WS}  scheme: ${SCHEME}"
            xcode-project build-ipa \
              --workspace "${WS}" \
              --scheme "${SCHEME}" \
              --archive-flags "${ARCHIVE_FLAGS}" \
              --export-options "${EXPORT_PLIST}"
          else
            echo "Using project: ${PROJ}  scheme: ${SCHEME}"
            xcode-project build-ipa \
              --project "${PROJ}" \
              --scheme "${SCHEME}" \
              --archive-flags "${ARCHIVE_FLAGS}" \
              --export-options "${EXPORT_PLIST}"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/Archives/**/*
