workflows:
  ios_release:
    name: iOS Release (TestFlight)
    integrations:
      app_store_connect: PartyPin

    environment:
      flutter: stable
      xcode: latest
      vars:
        CM_EXPORT_METHOD: app-store

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: Install signing (use uploaded p12 + mobileprovision)
        script: |
          set -e
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Export signing vars
        script: |
          set -e
          PF=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision | head -n1)
          INFO=$(/usr/bin/security cms -D -i "$PF")
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin <<< "$INFO")
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$INFO")
          TEAM_ID=$(/usr/libexec/PlistBuddy -c 'Print :TeamIdentifier:0' /dev/stdin <<< "$INFO")
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV
          echo "DEVELOPMENT_TEAM=$TEAM_ID" >> $CM_ENV
          echo "Using PROFILE_NAME=$PROFILE_NAME, PROFILE_UUID=$PROFILE_UUID, TEAM_ID=$TEAM_ID"

      - name: Debug signing
        script: |
          security find-identity -v -p codesigning || true
          ls -l ~/Library/MobileDevice/Provisioning\ Profiles || true
          xcodebuild -showBuildSettings -workspace ios/Runner.xcworkspace -scheme Runner | grep PRODUCT_BUNDLE_IDENTIFIER

      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-flags "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=${DEVELOPMENT_TEAM} PROVISIONING_PROFILE_SPECIFIER=${PROFILE_UUID} CODE_SIGN_IDENTITY=Apple\ Distribution"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
