workflows:
  ios_inline_signing:
    name: iOS Inline Signing (nur Workflow)
    environment:
      vars:
        SCHEME: "App"
        EXPORT_METHOD: "app-store"
        P12_BASE64: "MIINGgIBAzCCDMgGCSqGSIb3DQEHAaCCDLkEggy1MIIMsTCCBuoGCSqGSIb3DQEHBqCCBtswggbXAgEAMIIG0AYJKoZIhvcNAQcBMF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBAdL1LKBpFSFOoFjkqIEDU7AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ6VZan2d5s5FcLkHKL9+55oCCBmAhTYG3xU19ISegrMlGJ9NfSHeLHKRy+z5cdNBOG0V9l0OZJfYCQf8AZlOZaUOxJX3k+o3l8t09+RZIhWHbklN3lKZjVCejRfDG2a1pieWH0D9Icp4/dCJgGdcTHpWQBX1cTOunLpcOHlKZ1FPCk6UsNYrOfTtzOyR6gOZzNPzrRv3WjQsgYuLSV9Oyz9/M2Aqul/R3O/G4AHQ/mVpl2nmKCDROpmoya2P3tNodsH/dYF2rS4s+mpVh1Cxhfqjo6r7CtMB/x7fKeB0vcIBxqTGmfyZPIMuCAcPEdR2uX501OtIF+jexZmlJbvol9PpuZH9yk3CUg1wm6+YP55RVStcZQdoSuUFBk4VFMnuonMBZp7CvFkJCS6yAwNB+fynFMOXYeD7Vx9lqXHr1w0ggII3VLp0jZDId42Ffm9QS7Pqx8x0g0RnGRZKXXbBJSVrtiAI6/AGZxKDwZJf/RYQsSZGMcFnni3qWPhtGBpyyb1+caY6dyMORCZY5FymsA1H5ggOIeUOkZfwyV8kkMvWNYtne8EGPZnvAhjuC+x8GfLudVryTz2mobZcCS7OcFbVZGoCXl7CTzAouAKUzhW6RGWO3HZMStHjrTjiX5dphbYZDQX6fOwjaBROjxkubHkh1Vy/KxNJ3ydJenJdkcoBSJec2fgMM0+puTD6hY0FqoUKWsO7J0KKLBQB3m62ru4DdOOtUh+S31nfo1SqClXHiHrtqXV8XOGFV0yqARV842Sqg6ZslWxtvxSRu8H6KTMdZ7VKhQyH9Mx23AU7uvxg1wRboa+QgGTFrGO6aIjbVzvC/IuqrYGmQMdFSDkIavTPsFSdJOfp/yhpr8NxFoz2iBU/vyWRJCULw4vH2iCEXq3wBp9YlxjIrfnJekf++BzFoTYkgdtQ1PduKB8r5GjOokTQWKXD3koNAoSurDctrSaIOyXasXqmMe4FmcCSoQSwUoC5w+r981FXfMaHAWqhjM+4/HPRN3yPzM5oI3Ffz9q58I5IG1oKdar7nuAF4ifSdR9GWixkPaW2Wb5xRKGiGKzd/S48MyvmPO2asCy39tt+HJUFM18uqlwVUCB+EOKMQYOe/+bjpIkIs9KOQxp/mKONX8ktaQ9v6gci+GXY77RuKe8Aszhlw3n+/LmtJVWyTPN0O6fYk87EMHoJY7jpNPsSxpi+Q/e5UWSa7seUgPhWKA2/bBAE2MRqM78KGgUQRbCNopJnQ8BWETx5G6q8m12uMFZnYX7gmEhT5q0+gn9Wx1mBYYk0rtgdEQpunUNn5KxwmzH6Km/w6j5ko1I3V0ul3+HTFlrfUFTf4HIZ1nUs1+/G24eZQY3COG4AKuTKUuQl0Rbdwt4sk+cJSlVdsxkfcV0BX1e6ZbZfmgLdcPu9+lByIcGT462rbSqoveVueSLZrRsIWEwPnMcx8zPUKCL3T4MqhVqGszWlI3OhJMNmttxNHuOnJSQwjGaEPYuEdYBoYQrW4iHx1SVHFJ6g05RIiZVSJNAQwiLVX+NXfrN5JQsgnBaxcu3ViDOa02StsOXph+yLHEEyfbaPKcwnzcFV8P0ZHu4/DXySDXBGf7MBFaYApHyk/rl68oYCQJ4iJOxFNrh29p4tdTWIQzicaZtVHrTuFHSIrzlzRbB/m/54GNIMqJCXI8QskhrMkPLjvRbqFAJDB9+J1v3F2ZE1RPfcljR6B24noW3WoyYl38Vzq34xJtIBcYub3e+6DHNTwX5LseBEaQz6DzPcLC2KccSJpJIKOHSF4A223eSTYReKSQWNKYuwckpfWeMKZswbn6TYfSGJno59bXAq1kaDWVgjGN0sYGhj0ZslxHH6KTIiK++nIy0OG980/agdsjGhopBfinP+yfg6k9cYpqhtSFPfnAe4ODNZS4j9pMRWLuTjOA045yX4w5v4ySzFHHPIJpoQZ5OGeBPGeszJbXvtyABxgH5wjOqMn5MEoO/G7pDRCqiALBhTQacVWFm6OIuAbeYA6xrHTjCV0Lt0Slw4vsCi5EdD5LcZHjwTZzK5LxsH1cpYUdqQJ0VcAKZzCTRQBGuXeAor0DHh93FQ7+kfFRQPCCBpuPchjQ2WbXPZ8NkiBSuv9TJP8AhtXaDBS1wXB54C1AVCTFRQgx7SGUrlav5YUKhDk1O5nezrbRwt/PebxOrc6AAdC+ZaXlQ9h2Va//k8wggW/BgkqhkiG9w0BBwGgggWwBIIFrDCCBagwggWkBgsqhkiG9w0BDAoBAqCCBTkwggU1MF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBDQSQXrUXhjOYjATYshh5P7AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQGmd4OUt1W+zZntQ2dDS4VwSCBNDnvTPYiAx9YcH/zQeW/K8IL0pRkJH5MFGDJ+sz5dOib66IO9Amw/cvAaLZ/YGpmRBEkSBENIi4EAYdZrtpyHVMonqG9x1qX6qF7hPg8QiNmcObBjacu0tsZDzxJRngqQaKOtl39WMBHTW15unPXRYnEYl6tSU3x7XSzHZ4NJ7p5R89o0pMIRpaSZHXbfrONCdQIbDiQwSSyGTZ42RAk20TVTH7V+ONsqPHOee17NdPxBEOsPaDwUY0NQkHEk+2MSbqmjd3cUXdoZXieyvjjj/ueXRzFnGcyCSCXEMT6U1p1vqhBAOa1/BPboGEX2kRMkPYuOoPmoDiA/Yrx+U0KF1iq3J9GgikHrGvRAnvyfgIW7Q8AguoriDQ1l5UPWdq2KWRk3HxGNBrRKtSqufq2fvYdqVN+ztysuQEWevDN7aaycdogK4zSoooWq6cw7L1kVWCvkO3EvZvkd5Kkff7807ZKqJQpNlan1AIsI6K+WLyi/yPE0u0PfFIO8lfojmuX8I9ahKDV5Y3Po3Pl1QpeeTXK76ZUMIvX/fDEAu4BGY1zgJ8Onuo5Ob6QasK7pF98dmAKpDfe4c9qRw/A3LgrDfNnmIfiLvFR84JkzwvGZxlkec51trygFJDt7SRwejMa9uzV2DIsdfvMkecPNLbsHJ4WIKPeduzPKJZyxOe/N4a9doX92ixzUGit/keYZr4Tb18URRPYbYOZixQUemEdDq03rMbM5PmDNIX0TLp03FbogwAaAXI5gO5DwQ+4YDGKpVlXesR57Imk3tcfWVttStRcDskCweVTeB5STkL7RBr6fzroxoYLe7C3B8GvDAfC5uWr7LFalxMd1s0bksrVFMamHEaOGb4w8M7K/e8aOYb6CHZUW0fj5g0HqUcOvP9Wf215pLRCtue7lwECS1939pEYv/64ejfR69ItXK0qm5A9BNhKDquYL1wFm5ddnPtxkFtaP8q4vpNlvKn4G0sl3o4kbd0VI+N5p8AYnEj0j9AZcOycctShYu11AtmUFK1hui3+kLkSZbz1M1Ub7/yJomIUSKxXwTxyrE9eM51EN5geWyGv2ZQ4Atd6HWlZTnAVHXCnHrXqrL14zDXSCh5xPC8DB3NB7RHjWmO6jf4IL+Op2zF7GhqOns42zJOuBDvMq7+XFIH9IHIwkgpohalGIlWrly+M2N+jtgCkj7gkUQlg/2C/YydrnLq9B8hWlrOytIizzAaQJz2uY4fitWnK8Ma7XMP/PyvjDq+9jDON52ECXJhfvEZ2J4RaxlET/HLP6NFxllbZX+CbkptNgFqbSCLIAuFJtN4swmmfc3I7pkZCHtYZt7JNOBZPtV6AcR8bnXv73kvOE4SdwcEUrL7rNSVTcnPpi8ywScT6J+rvS9JAJeViiFj49vefRF0VN9KlG/SqQP/04O6gl8NqlHMRcseoC4ivCXmlcKq/h1EWNwMc2z02JB+tXnuSU6eRykSqAznjYbxEFmIvoI1FZ2FYTPiS8P2LJCX+MCNZ0aJzUhRgqTssZG9EUwcX6VToSKTaRW1j82iPprni2lczcm6TjJWH81OQczQqcVYgHtaiD29gPpqGXc8ULrpcvtSop6lkdcMOjxPsMRqOeHhMDz1XDHaN3tifdVnXY5H96avdMdN/DFYMCMGCSqGSIb3DQEJFTEWBBSI9sO5FWCMYWfLfyxQB7eUZwqQ8zAxBgkqhkiG9w0BCRQxJB4iAFAAYQByAHQAeQBQAGkAbgBTAGkAZwBuAGEAdAB1AHIAZTBJMDEwDQYJYIZIAWUDBAIBBQAEIBVsIffB93ng+h5nbeyrXFyo3pIzErauD+kM0U6P9aCtBBBUAlQ0znxosKMKADrUdminAgIIAA=="
        MOBILEPROVISION_BASE64: "MII2WgYJKoZIhvcNAQcCoII2SzCCNkcCAQExCzAJBgUrDgMCGgUAMIImZwYJKoZIhvcNAQcBoIImWASCJlQ8P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCI/Pgo8IURPQ1RZUEUgcGxpc3QgUFVCTElDICItLy9BcHBsZS8vRFREIFBMSVNUIDEuMC8vRU4iICJodHRwOi8vd3d3LmFwcGxlLmNvbS9EVERzL1Byb3BlcnR5TGlzdC0xLjAuZHRkIj4KPHBsaXN0IHZlcnNpb249IjEuMCI+CjxkaWN0PgoJPGtleT5BcHBJRE5hbWU8L2tleT4KCTxzdHJpbmc+UGFydHlwaW4gPC9zdHJpbmc+Cgk8a2V5PkFwcGxpY2F0aW9uSWRlbnRpZmllclByZWZpeDwva2V5PgoJPGFycmF5PgoJPHN0cmluZz43QlNCQjdZNDg1PC9zdHJpbmc+Cgk8L2FycmF5PgoJPGtleT5DcmVhdGlvbkRhdGU8L2tleT4KCTxkYXRlPjIwMjUtMTAtMTlUMTg6MzI6MjRaPC9kYXRlPgoJPGtleT5QbGF0Zm9ybTwva2V5PgoJPGFycmF5PgoJCTxzdHJpbmc+aU9TPC9zdHJpbmc+CgkJPHN0cmluZz54ck9TPC9zdHJpbmc+CgkJPHN0cmluZz52aXNpb25PUzwvc3RyaW5nPgoJPC9hcnJheT4KCTxrZXk+SXNYY29kZU1hbmFnZWQ8L2tleT4KCTxmYWxzZS8+Cgk8a2V5PkRldmVsb3BlckNlcnRpZmljYXRlczwva2V5PgoJPGFycmF5PgoJCTxkYXRhPk1JSUZzVENDQkptZ0F3SUJBZ0lRSWVncXdSdTV2WjI0VHlWLzhJVExKakFOQmdrcWhraUc5dzBCQVFzRkFEQjFNVVF3UWdZRFZRUURERHRCY0hCc1pTQlhiM0pzWkhkcFpHVWdSR1YyWld4dmNHVnlJRkpsYkdGMGFXOXVjeUJEWlhKMGFXWnBZMkYwYVc5dUlFRjFkR2h2Y21sMGVURUxNQWtHQTFVRUN3d0NSek14RXpBUkJnTlZCQW9NQ2tGd2NHeGxJRWx1WXk0eEN6QUpCZ05WQkFZVEFsVlRNQjRYRFRJMU1UQXhPREl4TlRrMU9Gb1hEVEkyTVRBeE9ESXhOVGsxTjFvd2dZd3hHakFZQmdvSmtpYUprL0lzWkFFQkRBbzNRbE5DUWpkWk5EZzFNVFl3TkFZRFZRUUREQzFwVUdodmJtVWdSR2x6ZEhKcFluVjBhVzl1T2lCVGIyNXFZU0JGWjJkbGNpQW9OMEpUUWtJM1dUUTROU2t4RXpBUkJnTlZCQXNNQ2pkQ1UwSkNOMWswT0RVeEZEQVNCZ05WQkFvTUMxTnZibXBoSUVWbloyVnlNUXN3Q1FZRFZRUUdFd0pCVkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTZKVnYrb1BkRWF3T0NuMDlrVmtvRm0vb2pXR2F4MjUvdEFmMVpiQXJqSFd2aHFYYUNqNy9rRFBRcmhxQTNWeHJqdmpWUEtYN2ZHZjVXMjFjQW9JeFgyamFIcmlhYXgzZ1hhU2FXbUpwb01QbmF0Wkh0amFIMjZjL2EwOG5rREJVenV6ZmtDMU1VOTRqVEI4bjVVSldrOHZiMzVWQUVmWUMxRmNCRzZ3OTdRQWh2TVhreE9RaXB0QnAwd2YxaU4wMy84UmdMUlRxSEZaSHoyNEJqVS9EWkZKTGhjTnZSU0FYbGw5akpPUzgwSXMyOHlxSzJNdTBKWmxaeTFjQ3c5Qk5jQUNacXZhVS81T2xVMG56MlpRRytMZVovTTZQREJuTVVrNG9xZTlRTFNQNTNRYlg3KzNpa0xUZFNYTDJBMkhkVUJOa0thaHRkMERxc0JXRmltR0owQ0F3RUFBYU9DQWlNd2dnSWZNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVDZjdBRlpENXIyUUtraEs1SmloakRKZnNwN0l3Y0FZSUt3WUJCUVVIQVFFRVpEQmlNQzBHQ0NzR0FRVUZCekFDaGlGb2RIUndPaTh2WTJWeWRITXVZWEJ3YkdVdVkyOXRMM2QzWkhKbk15NWtaWEl3TVFZSUt3WUJCUVVITUFHR0pXaDBkSEE2THk5dlkzTndMbUZ3Y0d4bExtTnZiUzl2WTNOd01ETXRkM2RrY21jek1ESXdnZ0VlQmdOVkhTQUVnZ0VWTUlJQkVUQ0NBUTBHQ1NxR1NJYjNZMlFGQVRDQi96Q0J3d1lJS3dZQkJRVUhBZ0l3Z2JZTWdiTlNaV3hwWVc1alpTQnZiaUIwYUdseklHTmxjblJwWm1sallYUmxJR0o1SUdGdWVTQndZWEowZVNCaGMzTjFiV1Z6SUdGalkyVndkR0Z1WTJVZ2IyWWdkR2hsSUhSb1pXNGdZWEJ3YkdsallXSnNaU0J6ZEdGdVpHRnlaQ0IwWlhKdGN5QmhibVFnWTI5dVpHbDBhVzl1Y3lCdlppQjFjMlVzSUdObGNuUnBabWxqWVhSbElIQnZiR2xqZVNCaGJtUWdZMlZ5ZEdsbWFXTmhkR2x2YmlCd2NtRmpkR2xqWlNCemRHRjBaVzFsYm5SekxqQTNCZ2dyQmdFRkJRY0NBUllyYUhSMGNITTZMeTkzZDNjdVlYQndiR1V1WTI5dEwyTmxjblJwWm1sallYUmxZWFYwYUc5eWFYUjVMekFXQmdOVkhTVUJBZjhFRERBS0JnZ3JCZ0VGQlFjREF6QWRCZ05WSFE0RUZnUVU1QnF2WVRZWEoremZXdHVUUlN0RitmMks2Nnd3RGdZRFZSMFBBUUgvQkFRREFnZUFNQk1HQ2lxR1NJYjNZMlFHQVFRQkFmOEVBZ1VBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFEVi92cDQwZ0UwdXJVZE1rMzZFdVFHVkdhR0ZVUExlSmRrWlJyTDVDNlJOSWZHMGplNEJnc2JkYjJ6Y2MzYitnT2FpY2ZuSytabFBXaWtNa0x2a043ckduTVZOblE5Y0tKMGNiU01OYXdDRXFKWXdXYmdQakNFbXN0OHJkTWJHUFFHSzhjZ1VVTEJwZmlTMzVZdVA3eFhFYjVqdXR6MDhuajZwZDJuZllJVWxxNUl1aFY2dXk0U3NIZVJxdmlFVHpBWlZ3R3FWWTMrNEVnbDJidEp6KzVaTUgzNTdOSDNmanJVcGllNkUrTHVBVGdGQ1FuU1UvWlJiMVZ1VUZpVHg4TTJjaGRXWm5MbUV3bzIvSEc3ak9ZcHJLZWxSMGVSVjdUMW1XaTFhY2JaMENrb2RIOElZRFpjVHFFc3d0dEpTT3VXRkl5cW95aHFabW1Iak9zQTdpVmw8L2RhdGE+Cgk8L2FycmF5PgoKCTxrZXk+REVSLUVuY29kZWQtUHJvZmlsZTwva2V5PgoJPGRhdGE+TUlJUFJnWUpLb1pJaHZjTkFRY0NvSUlQTnpDQ0R6TUNBUUV4RFRBTEJnbGdoa2dCWlFNRUFnRXdnZ1VGQmdrcWhraUc5dzBCQndHZ2dnVDJCSUlFOGpHQ0JPNHdEQXdIVm1WeWMybHZiZ0lCQVRBTkRBaFFVRkZEYUdWamF3RUJBREFRREFwVWFXMWxWRzlNYVhabEFnSUJiREFUREE1SmMxaGpiMlJsVFdGdVlXZGxaQUVCQURBV0RBbEJjSEJKUkU1aGJXVU1DVkJoY25SNWNHbHVJREFYREFoVVpXRnRUbUZ0WlF3TFUyOXVhbUVnUldkblpYSXdIUXdNUTNKbFlYUnBiMjVFWVhSbEZ3MHlOVEV3TVRreE9ETXlNalJhTUI0TURsUmxZVzFKWkdWdWRHbG1hV1Z5TUF3TUNqZENVMEpDTjFrME9EVXdId3dPUlhod2FYSmhkR2x2YmtSaGRHVVhEVEkyTVRBeE9ESXhOVGsxTjFvd0lBd1hVSEp2Wm1sc1pVUnBjM1J5YVdKMWRHbHZibFI1Y0dVTUJWTlVUMUpGTUNFTUJFNWhiV1VNR1ZCaGNuUjVVR2x1SUVGd2NGTjBiM0psSUZCeWIyWnBiR1V3SVF3SVVHeGhkR1p2Y20wd0ZRd0RhVTlUREFSNGNrOVREQWgyYVhOcGIyNVBVekFyREJ0QmNIQnNhV05oZEdsdmJrbGtaVzUwYVdacFpYSlFjbVZtYVhnd0RBd0tOMEpUUWtJM1dUUTROVEFzREFSVlZVbEVEQ1EyWkRVNE56TTROQzA0WmpRMUxUUXdaalF0WVRVeE5pMDNNV1ZoTW1ZeE5tVXlPREV3T3d3VlJHVjJaV3h2Y0dWeVEyVnlkR2xtYVdOaGRHVnpNQ0lFSURLNUZzaTBHcTUvZFQ3WG05c3NDS29kWVo0UXJIRE11RmV4Y1NxdmVzd0JNSUlERlF3TVJXNTBhWFJzWlcxbGJuUnpjSUlEQXdJQkFiQ0NBdnd3T0F3V1lYQndiR2xqWVhScGIyNHRhV1JsYm5ScFptbGxjZ3dlTjBKVFFrSTNXVFE0TlM1amIyMHVURUZzWVdKekxuQmhjblI1Y0dsdU1CME1EMkZ3Y3kxbGJuWnBjbTl1YldWdWRBd0tjSEp2WkhWamRHbHZiakFZREJOaVpYUmhMWEpsY0c5eWRITXRZV04wYVhabEFRSC9NQ3dNSDJOdmJTNWhjSEJzWlM1a1pYWmxiRzl3WlhJdVlYQndiR1Z6YVdkdWFXNHdDUXdIUkdWbVlYVnNkREFyRENaamIyMHVZWEJ3YkdVdVpHVjJaV3h2Y0dWeUxtUmxZMnhoY21Wa0xXRm5aUzF5WVc1blpRRUIvekFuRENOamIyMHVZWEJ3YkdVdVpHVjJaV3h2Y0dWeUxtbHVMV0Z3Y0Mxd1lYbHRaVzUwY3pBQU1DWU1JV052YlM1aGNIQnNaUzVrWlhabGJHOXdaWEl1YldWemMyRm5hVzVuTFdGd2NBRUIvekJtRERKamIyMHVZWEJ3YkdVdVpHVjJaV3h2Y0dWeUxtNWxkSGR2Y210cGJtY3VjMnhwWTJsdVp5NWhjSEJqWVhSbFoyOXllVEF3REJKamIyMXRkVzVwWTJGMGFXOXVMVGt3TURBTUNtZGhiV1Z6TFRZd01UUU1Ebk4wY21WaGJXbHVaeTA1TURBeE1JR3NERFpqYjIwdVlYQndiR1V1WkdWMlpXeHZjR1Z5TG01bGRIZHZjbXRwYm1jdWMyeHBZMmx1Wnk1MGNtRm1abWxqWTJGMFpXZHZjbmt3Y2d3T1pHVm1ZWFZzZEhOc2FXTmxMVEVNQjNacFpHVnZMVElNREdKaFkydG5jbTkxYm1RdE13d0hkbTlwWTJVdE5Bd1BZMkZzYkhOcFoyNWhiR2x1WnkwMURCQnlaWE53YjI1emFYWmxaR0YwWVMwMkRBMWhkbk4wY21WaGJXbHVaeTAzREE1eVpYTndiMjV6YVhabFlYWXRPREJCREROamIyMHVZWEJ3YkdVdVpHVjJaV3h2Y0dWeUxuTmxibk5wZEdsMlpXTnZiblJsYm5SaGJtRnNlWE5wY3k1amJHbGxiblF3Q2d3SVlXNWhiSGx6YVhNd01Rd2pZMjl0TG1Gd2NHeGxMbVJsZG1Wc2IzQmxjaTUwWldGdExXbGtaVzUwYVdacFpYSU1DamRDVTBKQ04xazBPRFV3RXd3T1oyVjBMWFJoYzJzdFlXeHNiM2NCQVFBd09Rd1dhMlY1WTJoaGFXNHRZV05qWlhOekxXZHliM1Z3Y3pBZkRBdzNRbE5DUWpkWk5EZzFMaW9NRDJOdmJTNWhjSEJzWlM1MGIydGxicUNDQ0R3d2dnSkRNSUlCeWFBREFnRUNBZ2d0eGZ5STBzVkxsVEFLQmdncWhrak9QUVFEQXpCbk1Sc3dHUVlEVlFRRERCSkJjSEJzWlNCU2IyOTBJRU5CSUMwZ1J6TXhKakFrQmdOVkJBc01IVUZ3Y0d4bElFTmxjblJwWm1sallYUnBiMjRnUVhWMGFHOXlhWFI1TVJNd0VRWURWUVFLREFwQmNIQnNaU0JKYm1NdU1Rc3dDUVlEVlFRR0V3SlZVekFlRncweE5EQTBNekF4T0RFNU1EWmFGdzB6T1RBME16QXhPREU1TURaYU1HY3hHekFaQmdOVkJBTU1Fa0Z3Y0d4bElGSnZiM1FnUTBFZ0xTQkhNekVtTUNRR0ExVUVDd3dkUVhCd2JHVWdRMlZ5ZEdsbWFXTmhkR2x2YmlCQmRYUm9iM0pwZEhreEV6QVJCZ05WQkFvTUNrRndjR3hsSUVsdVl5NHhDekFKQmdOVkJBWVRBbFZUTUhZd0VBWUhLb1pJemowQ0FRWUZLNEVFQUNJRFlnQUVtT2t2UFVCeXBPMlRJbktCRXh6ZEVKWHh4YU5PY2R3VUZ0a081YVlGS25ka2UxOU9PTk83SEVTMWYvVWZ0akppWGNucGhGdFBNRThSV2dEOVdGZ01wZlVQTEUwSFJ4TjEycGVYbDI4eFhPMHJuWHNnTzlpNVZObGVtYVE2VVFveG8wSXdRREFkQmdOVkhRNEVGZ1FVdTdEZW9WZ3ppSnFraXBuZXZyM3JyOXJMSktzd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlZIUThCQWY4RUJBTUNBUVl3Q2dZSUtvWkl6ajBFQXdNRGFBQXdaUUl4AU..."
        P12_PASSWORD: "Yamahayz85"

    scripts:
      - name: Install signing (inline)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          require() { [[ -n "${!1:-}" ]] || { echo "$1 leer"; exit 1; }; }
          require P12_BASE64
          require MOBILEPROVISION_BASE64
          require P12_PASSWORD

          mkdir -p /tmp/signing
          python3 - <<'PY'
          import os, base64, pathlib, re, sys, binascii
          def clean_b64(s: str) -> str:
              s = ''.join(s.split()).strip('"').strip("'")
              if not re.fullmatch(r'[A-Za-z0-9+/=]+', s):
                  print("Base64 enthält ungültige Zeichen", file=sys.stderr); sys.exit(2)
              s += "=" * ((4 - len(s) % 4) % 4)
              return s
          def write_b64(env, path):
              raw = os.environ[env]
              b64 = clean_b64(raw)
              try:
                  data = base64.b64decode(b64, validate=False)
              except binascii.Error:
                  print(f"{env} konnte nicht base64-dekodiert werden", file=sys.stderr); sys.exit(2)
              pathlib.Path(path).write_bytes(data)
          write_b64('P12_BASE64', '/tmp/signing/cert.p12')
          write_b64('MOBILEPROVISION_BASE64', '/tmp/signing/profile.mobileprovision')
          PY

          /usr/bin/openssl pkcs12 -info -in /tmp/signing/cert.p12 -passin pass:"$P12_PASSWORD" -nodes -nokeys >/dev/null \
            || { echo "Ungültiges .p12 oder falsches Passwort"; exit 1; }

          keychain initialize
          keychain add-certificates --certificate /tmp/signing/cert.p12 --certificate-password "$P12_PASSWORD"

          PROV="/tmp/signing/profile.mobileprovision"
          [[ -s "$PROV" ]] || { echo "Provisioning-Profile leer"; exit 1; }

          # CMS zu Plist decodieren, sonst Abbruch
          if ! /usr/bin/security cms -D -i "$PROV" -o /tmp/signing/profile.plist >/dev/null 2>&1; then
            echo "Provisioning-Profile ungültig: CMS lässt sich nicht lesen"; exit 1
          fi

          # UUID extrahieren
          UUID="$(/usr/bin/plutil -extract UUID raw -o - /tmp/signing/profile.plist 2>/dev/null || true)"
          if [[ -z "$UUID" ]]; then
            UUID="$(/usr/libexec/PlistBuddy -c 'Print :UUID' /tmp/signing/profile.plist 2>/dev/null || true)"
          fi
          [[ -n "$UUID" ]] || { echo "Profil ungültig: UUID nicht gefunden"; exit 1; }

          DST_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$DST_DIR"
          cp "$PROV" "$DST_DIR/$UUID.mobileprovision"

          xcode-project use-profiles

      - name: Build IPA
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          # iOS-Workspace/Projekt suchen. macOS ausschließen.
          WS="$(find ios -maxdepth 3 -name "*.xcworkspace" -print -quit 2>/dev/null || true)"
          if [[ -z "${WS}" ]]; then
            WS="$(find . -path "./macos" -prune -o -name "*.xcworkspace" -print -quit || true)"
          fi

          PROJ=""
          if [[ -z "${WS}" ]]; then
            PROJ="$(find ios -maxdepth 3 -name "*.xcodeproj" -print -quit 2>/dev/null || true)"
            if [[ -z "${PROJ}" ]]; then
              PROJ="$(find . -path "./macos" -prune -o -name "*.xcodeproj" -print -quit || true)"
            fi
          fi
          [[ -n "${WS}" || -n "${PROJ}" ]] || { echo "Kein iOS .xcworkspace oder .xcodeproj gefunden"; exit 1; }

          # Scheme automatisch ermitteln, wenn nicht gesetzt
          if [[ -z "${SCHEME:-}" ]]; then
            if [[ -n "${WS}" ]]; then
              SCHEME="$(
                /usr/bin/xcodebuild -workspace "${WS}" -list -json \
                | /usr/bin/python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("workspace",{}).get("schemes",[":none:"])[0])'
              )"
            else
              SCHEME="$(
                /usr/bin/xcodebuild -project "${PROJ}" -list -json \
                | /usr/bin/python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("project",{}).get("schemes",[":none:"])[0])'
              )"
            fi
          fi
          [[ -n "${SCHEME}" && "${SCHEME}" != ":none:" ]] || { echo "Konnte Scheme nicht ermitteln. Setze SCHEME explizit."; exit 1; }

          # ExportOptions statt --export-method
          EXPORT_METHOD="${EXPORT_METHOD:-app-store}"
          EXPORT_PLIST="/tmp/ExportOptions.plist"
          cat > "${EXPORT_PLIST}" <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>${EXPORT_METHOD}</string>
            <key>signingStyle</key><string>manual</string>
            <key>destination</key><string>export</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>uploadBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          DEST="-destination 'generic/platform=iOS'"

          if [[ -n "${WS}" ]]; then
            echo "Using workspace: ${WS}  scheme: ${SCHEME}"
            xcode-project build-ipa \
              --workspace "${WS}" \
              --scheme "${SCHEME}" \
              --archive-flags "${DEST}" \
              --export-options "${EXPORT_PLIST}"
          else
            echo "Using project: ${PROJ}  scheme: ${SCHEME}"
            xcode-project build-ipa \
              --project "${PROJ}" \
              --scheme "${SCHEME}" \
              --archive-flags "${DEST}" \
              --export-options "${EXPORT_PLIST}"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/Archives/**/*
