workflows:
  ios_release:
    name: iOS Release (TestFlight)
    integrations:
      app_store_connect: PartyPin
    environment:
      flutter: stable
      xcode: latest
      vars:
        CM_EXPORT_METHOD: app-store

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: Use signing (uploaded p12 + mobileprovision)
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Debug signing
        script: |
          security find-identity -v -p codesigning
          ls -l ~/Library/MobileDevice/Provisioning\ Profiles
          xcodebuild -showBuildSettings -workspace ios/Runner.xcworkspace -scheme Runner | grep PRODUCT_BUNDLE_IDENTIFIER

      - name: Build IPA
        script: xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
