workflows:
  ios_inline_signing:
    name: iOS Inline Signing (nur Workflow)
    environment:
      vars:
        SCHEME: "Runner"
        EXPORT_METHOD: "app-store"

        # <<< DEINE BASE64-WERTE HIER LASSEN >>>
        P12_BASE64: "MIINGgIBAzCCDMgGCSqGSIb3DQEHAaCCDLkEggy1MIIMsTCCBuoGCSqGSIb3DQEHBqCCBtswggbXAgEAMIIG0AYJKoZIhvcNAQcBMF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBAdL1LKBpFSFOoFjkqIEDU7AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ6VZan2d5s5FcLkHKL9+55oCCBmAhTYG3xU19ISegrMlGJ9NfSHeLHKRy+z5cdNBOG0V9l0OZJfYCQf8AZlOZaUOxJX3k+o3l8t09+RZIhWHbklN3lKZjVCejRfDG2a1pieWH0D9Icp4/dCJgGdcTHpWQBX1cTOunLpcOHlKZ1FPCk6UsNYrOfTtzOyR6gOZzNPzrRv3WjQsgYuLSV9Oyz9/M2Aqul/R3O/G4AHQ/mVpl2nmKCDROpmoya2P3tNodsH/dYF2rS4s+mpVh1Cxhfqjo6r7CtMB/x7fKeB0vcIBxqTGmfyZPIMuCAcPEdR2uX501OtIF+jexZmlJbvol9PpuZH9yk3CUg1wm6+YP55RVStcZQdoSuUFBk4VFMnuonMBZp7CvFkJCS6yAwNB+fynFMOXYeD7Vx9lqXHr1w0ggII3VLp0jZDId42Ffm9QS7Pqx8x0g0RnGRZKXXbBJSVrtiAI6/AGZxKDwZJf/RYQsSZGMcFnni3qWPhtGBpyyb1+caY6dyMORCZY5FymsA1H5ggOIeUOkZfwyV8kkMvWNYtne8EGPZnvAhjuC+x8GfLudVryTz2mobZcCS7OcFbVZGoCXl7CTzAouAKUzhW6RGWO3HZMStHjrTjiX5dphbYZDQX6fOwjaBROjxkubHkh1Vy/KxNJ3ydJenJdkcoBSJec2fgMM0+puTD6hY0FqoUKWsO7J0KKLBQB3m62ru4DdOOtUh+S31nfo1SqClXHiHrtqXV8XOGFV0yqARV842Sqg6ZslWxtvxSRu8H6KTMdZ7VKhQyH9Mx23AU7uvxg1wRboa+QgGTFrGO6aIjbVzvC/IuqrYGmQMdFSDkIavTPsFSdJOfp/yhpr8NxFoz2iBU/vyWRJCULw4vH2iCEXq3wBp9YlxjIrfnJekf++BzFoTYkgdtQ1PduKB8r5GjOokTQWKXD3koNAoSurDctrSaIOyXasXqmMe4FmcCSoQSwUoC5w+r981FXfMaHAWqhjM+4/HPRN3yPzM5oI3Ffz9q58I5IG1oKdar7nuAF4ifSdR9GWixkPaW2Wb5xRKGiGKzd/S48MyvmPO2asCy39tt+HJUFM18uqlwVUCB+EOKMQYOe/+bjpIkIs9KOQxp/mKONX8ktaQ9v6gci+GXY77RuKe8Aszhlw3n+/LmtJVWyTPN0O6fYk87EMHoJY7jpNPsSxpi+Q/e5UWSa7seUgPhWKA2/bBAE2MRqM78KGgUQRbCNopJnQ8BWETx5G6q8m12uMFZnYX7gmEhT5q0+gn9Wx1mBYYk0rtgdEQpunUNn5KxwmzH6Km/w6j5ko1I3V0ul3+HTFlrfUFTf4HIZ1nUs1+/G24eZQY3COG4AKuTKUuQl0Rbdwt4sk+cJSlVdsxkfcV0BX1e6ZbZfmgLdcPu9+lByIcGT462rbSqoveVueSLZrRsIWEwPnMcx8zPUKCL3T4MqhVqGszWlI3OhJMNmttxNHuOnJSQwjGaEPYuEdYBoYQrW4iHx1SVHFJ6g05RIiZVSJNAQwiLVX+NXfrN5JQsgnBaxcu3ViDOa02StsOXph+yLHEEyfbaPKcwnzcFV8P0ZHu4/DXySDXBGf7MBFaYApHyk/rl68oYCQJ4iJOxFNrh29p4tdTWIQzicaZtVHrTuFHSIrzlzRbB/m/54GNIMqJCXI8QskhrMkPLjvRbqFAJDB9+J1v3F2ZE1RPfcljR6B24noW3WoyYl38Vzq34xJtIBcYub3e+6DHNTwX5LseBEaQz6DzPcLC2KccSJpJIKOHSF4A223eSTYReKSQWNKYuwckpfWeMKZswbn6TYfSGJno59bXAq1kaDWVgjGN0sYGhj0ZslxHH6KTIiK++nIy0OG980/agdsjGhopBfinP+yfg6k9cYpqhtSFPfnAe4ODNZS4j9pMRWLuTjOA045yX4w5v4ySzFHHPIJpoQZ5OGeBPGeszJbXvtyABxgH5wjOqMn5MEoO/G7pDRCqiALBhTQacVWFm6OIuAbeYA6xrHTjCV0Lt0Slw4vsCi5EdD5LcZHjwTZzK5LxsH1cpYUdqQJ0VcAKZzCTRQBGuXeAor0DHh93FQ7+kfFRQPCCBpuPchjQ2WbXPZ8NkiBSuv9TJP8AhtXaDBS1wXB54C1AVCTFRQgx7SGUrlav5YUKhDk1O5nezrbRwt/PebxOrc6AAdC+ZaXlQ9h2Va//k8wggW/BgkqhkiG9w0BBwGgggWwBIIFrDCCBagwggWkBgsqhkiG9w0BDAoBAqCCBTkwggU1MF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBDQSQXrUXhjOYjATYshh5P7AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQGmd4OUt1W+zZntQ2dDS4VwSCBNDnvTPYiAx9YcH/zQeW/K8IL0pRkJH5MFGDJ+sz5dOib66IO9Amw/cvAaLZ/YGpmRBEkSBENIi4EAYdZrtpyHVMonqG9x1qX6qF7hPg8QiNmcObBjacu0tsZDzxJRngqQaKOtl39WMBHTW15unPXRYnEYl6tSU3x7XSzHZ4NJ7p5R89o0pMIRpaSZHXbfrONCdQIbDiQwSSyGTZ42RAk20TVTH7V+ONsqPHOee17NdPxBEOsPaDwUY0NQkHEk+2MSbqmjd3cUXdoZXieyvjjj/ueXRzFnGcyCSCXEMT6U1p1vqhBAOa1/BPboGEX2kRMkPYuOoPmoDiA/Yrx+U0KF1iq3J9GgikHrGvRAnvyfgIW7Q8AguoriDQ1l5UPWdq2KWRk3HxGNBrRKtSqufq2fvYdqVN+ztysuQEWevDN7aaycdogK4zSoooWq6cw7L1kVWCvkO3EvZvkd5Kkff7807ZKqJQpNlan1AIsI6K+WLyi/yPE0u0PfFIO8lfojmuX8I9ahKDV5Y3Po3Pl1QpeeTXK76ZUMIvX/fDEAu4BGY1zgJ8Onuo5Ob6QasK7pF98dmAKpDfe4c9qRw/A3LgrDfNnmIfiLvFR84JkzwvGZxlkec51trygFJDt7SRwejMa9uzV2DIsdfvMkecPNLbsHJ4WIKPeduzPKJZyxOe/N4a9doX92ixzUGit/keYZr4Tb18URRPYbYOZixQUemEdDq03rMbM5PmDNIX0TLp03FbogwAaAXI5gO5DwQ+4YDGKpVlXesR57Imk3tcfWVttStRcDskCweVTeB5STkL7RBr6fzroxoYLe7C3B8GvDAfC5uWr7LFalxMd1s0bksrVFMamHEaOGb4w8M7K/e8aOYb6CHZUW0fj5g0HqUcOvP9Wf215pLRCtue7lwECS1939pEYv/64ejfR69ItXK0qm5A9BNhKDquYL1wFm5ddnPtxkFtaP8q4vpNlvKn4G0sl3o4kbd0VI+N5p8AYnEj0j9AZcOycctShYu11AtmUFK1hui3+kLkSZbz1M1Ub7/yJomIUSKxXwTxyrE9eM51EN5geWyGv2ZQ4Atd6HWlZTnAVHXCnHrXqrL14zDXSCh5xPC8DB3NB7RHjWmO6jf4IL+Op2zF7GhqOns42zJOuBDvMq7+XFIH9IHIwkgpohalGIlWrly+M2N+jtgCkj7gkUQlg/2C/YydrnLq9B8hWlrOytIizzAaQJz2uY4fitWnK8Ma7XMP/PyvjDq+9jDON52ECXJhfvEZ2J4RaxlET/HLP6NFxllbZX+CbkptNgFqbSCLIAuFJtN4swmmfc3I7pkZCHtYZt7JNOBZPtV6AcR8bnXv73kvOE4SdwcEUrL7rNSVTcnPpi8ywScT6J+rvS9JAJeViiFj49vefRF0VN9KlG/SqQP/04O6gl8NqlHMRcseoC4ivCXmlcKq/h1EWNwMc2z02JB+tXnuSU6eRykSqAznjYbxEFmIvoI1FZ2FYTPiS8P2LJCX+MCNZ0aJzUhRgqTssZG9EUwcX6VToSKTaRW1j82iPprni2lczcm6TjJWH81OQczQqcVYgHtaiD29gPpqGXc8ULrpcvtSop6lkdcMOjxPsMRqOeHhMDz1XDHaN3tifdVnXY5H96avdMdN/DFYMCMGCSqGSIb3DQEJFTEWBBSI9sO5FWCMYWfLfyxQB7eUZwqQ8zAxBgkqhkiG9w0BCRQxJB4iAFAAYQByAHQAeQBQAGkAbgBTAGkAZwBuAGEAdAB1AHIAZTBJMDEwDQYJYIZIAWUDBAIBBQAEIBVsIffB93ng+h5nbeyrXFyo3pIzErauD+kM0U6P9aCtBBBUAlQ0znxosKMKADrUdminAgIIAA=="
        MOBILEPROVISION_BASE64: "MII2WgYJKoZIhvcNAQcCoII2SzCCNkcCAQExCzAJBgUrDgMCGgUAMIImZwYJKoZIhvcNAQcBoIImWASCJlQ8P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCI/Pgo8IURPQ1RZUEUgcGxpc3QgUFVCTElDICItLy9BcHBsZS8vRFREIFBMSVNUIDEuMC8vRU4iICJodHRwOi8vd3d3LmFwcGxlLmNvbS9EVERzL1Byb3BlcnR5TGlzdC0xLjAuZHRkIj4KPHBsaXN0IHZlcnNpb249IjEuMCI+CjxkaWN0PgoJPGtleT5BcHBJRE5hbWU8L2tleT4KCTxzdHJpbmc+UGFydHlwaW4gPC9zdHJpbmc+Cgk8a2V5PkFwcGxpY2F0aW9uSWRlbnRpZmllclByZWZpeDwva2V5PgoJPGFycmF5PgoJPHN0cmluZz43QlNCQjdZNDg1PC9zdHJpbmc+Cgk8L2FycmF5PgoJPGtleT5DcmVhdGlvbkRhdGU8L2tleT4KCTxkYXRlPjIwMjUtMTAtMTlUMTg6MzI6MjRaPC9kYXRlPgoJPGtleT5QbGF0Zm9ybTwva2V5PgoJPGFycmF5PgoJCTxzdHJpbmc+aU9TPC9zdHJpbmc+CgkJPHN0cmluZz54ck9TPC9zdHJpbmc+CgkJPHN0cmluZz52aXNpb25PUzwvc3RyaW5nPgoJPC9hcnJheT4KCTxrZXk+SXNYY29kZU1hbmFnZWQ8L2tleT4KCTxmYWxzZS8+Cgk8a2V5PkRldmVsb3BlckNlcnRpZmljYXRpb25zPC9rZXk+Cgk8YXJyYXk+CgkJPGRhdGE+TUlJRnNUQ0NCSm1nQXdJQkFnSVFJZWdxd1J1NXZaMjRUeVYvOElUTExpakFOQmdrcWhraUc5dzBCQVFzRkFEQjFNVVF3UWdZRFZRUURERHRCY0hCc1pTQlhiM0pzWkhkcFpHVWdSR1YyWld4dmNHVnlJRkpsYkdGMGFXOXVjeUJEWlhKMGFXWnBZMkYwYVc5dUlFRjFkR2h2Y21sMGVURUxNQWtHQTFVRUN3d0NSek14RXpBUkJnTlZCQW9NQ2tGd2NHeGxJRWx1WXk0eEN6QUpCZ05WQkFZVEFsVlRNQjRYRFRJMU1UQXhPREl4TlRrMU9Gb1hEVEkyTVRBeE9ESXhOVGsxTjFvd2dZd3hHakFZQmdvSmtpYUprL0lzWkFFQkRBbzNRbE5DUWpkWk5EZzFNVFl3TkFZRFZRUUREQzFwVUdodmJtVWdSR2x6ZEhKcFluVjBhVzl1T2lCVGIyNXFZU0JGWjJkbGNpQW9OMEpUUWtJM1dUUTROU2t4RXpBUkJnTlZCQXNNQ2pkQ1UwSkNOMWswT0RVeEZEQVNCZ05WQkFvTUMxTnZibXBoSUVWbloyVnlNUXN3Q1FZRFZRUUdFd0pCVkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTZKVnYrb1BkRWF3T0NuMDlrVmtvRm0vb2pXR2F4MjUvdEFmMVpiQXJqSFd2aHFYYUNqNy9rRFBRcmhxQTNWeHJqdmpWUEtYN2ZHZjVXMjFjQW9JeFgyamFIcmlhYXgzZ1hhU2FXbUpwb01QbmF0Wkh0amFIMjZjL2EwOG5rREJVenV6ZmtDMU1VOTRqVEI4bjVVSldrOHZiMzVWQUVmWUMxRmNCRzZ3OTdRQWh2TVhreE9RaXB0QnAwd2YxaU4wMy84UmdMUlRxSEZaSHoyNEJqVS9EWkZKTGhjTnZSU0FYbGw5akpPUzgwSXMyOHlxSzJNdTBKWmxaeTFjQ3c5Qk5jQUNacXZhVS81T2xVMG56MlpRRytMZVovTTZQREJuTVVrNG9xZTlRTFNQNTNRYlg3KzNpa0xUZFNYTDJBMkhkVUJOa0thaHRkMERxc0JXRmltR0owQ0F3RUFBYU9DQWlNd2dnSWZNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVDZjdBRlpENXIyUUtraEs1SmloakRKZnNwN0l3Y0FZSUt3WUJCUVVIQVFFRVpEQmlNQzBHQ0NzR0FRVUZCekFDaGlGb2RIUndPaTh2WTJWeWRITXVZWEJ3YkdVdVkyOXRMM2QzWkhKbk15NWtaWEl3TVFZSUt3WUJCUVVITUFHR0pXaDBkSEE2THk5dlkzTndMbUZ3Y0d4bExtTnZiUzl2WTNOd01ETXRkM2RrY21jek1ESXdnZ0VlQmdOVkhTQUVnZ0VWTUlJQkVUQ0NBUTBHQ1NxR1NJYjNZMlFGQVRDQi96Q0J3d1lJS3dZQkJRVUhBZ0l3Z2JZTWdiTlNaV3hwWVc1alpTQnZiaUIwYUdseklHTmxjblJwWm1sallYUmxJR0o1SUdGdWVTQndZWEowZVNCaGMzTjFiV1Z6SUdGalkyVndkR0Z1WTJVZ2IyWWdkR2hsSUhSb1pXNGdZWEJ3YkdsallXSnNaU0J6ZEdGdVpHRnlaQ0IwWlhKdGN5QmhibVFnWTI5dVpHbDBhVzl1Y3lCdlppQjFjMlVzSUdObGNuUnBabWxqWVhSbElIQnZiR2xqZVNCaGJtUWdZMlZ5ZEdsbWFXTmhkR2x2YmlCd2NtRmpkR2xqWlNCemRHRjBaVzFsYm5SekxqQTNCZ2dyQmdFRkJRY0NBUllyYUhSMGNITTZMeTkzZDNjdVlYQndiR1V1WTI5dEwyTmxjblJwWm1sallYUmxZWFYwYUc5eWFYUjVMekFXQmdOVkhTVUJBZjhFRERBS0JnZ3JCZ0VGQlFjREF6QWRCZ05WSFE0RUZnUVU1QnF2WVRZWEoremZXdHVUUlN0RitmMks2Nnd3RGdZRFZSMFBBUUgvQkFRREFnZUFNQk1HQ2lxR1NJYjNZMlFHQVFRQkFmOEVBZ1VBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFEVi92cDQwZ0UwdXJVZE1rMzZFdVFHVkdhR0ZVUExlSmRrWlJyTDVDNlJOSWZHMGplNEJnc2JkYjJ6Y2MzYitnT2FpY2ZuSytabFBXaWtNa0x2a043ckduTVZOblE5Y0tKMGNiU01OYXdDRXFKWXdXYmdQakNFbXN0OHJkTWJHUFFHSzhjZ1VVTEJwZmlTMzVZdVA3eFhFYjVqdXR6MDhuajZwZDJuZllJVWxxNUl1aFY2dXk0U3NIZVJxdmlFVHpBWlZ3R3FWWTMrNEVnbDJidEp6KzVaTUgzNTdOSDNmanJVcGllNkUrTHVBVGdGQ1FuU1UvWlJiMVZ1VUZpVHg4TTJjaGRXWm5MbUV3bzIvSEc3ak9ZcHJLZWxSMGVSVjdUMW1XaTFhY2JaMENrb2RIOElZRFpjVHFFc3d0dEpTT3VXRkl5cW95aHFabW1Iak9zQTdpVmw8L2RhdGE+"
        P12_PASSWORD: "Yamahayz85"

    scripts:
      - name: Install signing (inline)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          req(){ [[ -n "${!1:-}" ]] || { echo "$1 leer"; exit 1; }; }
          req P12_BASE64; req MOBILEPROVISION_BASE64; req P12_PASSWORD

          mkdir -p /tmp/signing

          # --- Zertifikat (.p12) strikt Base64 dekodieren ---
          python3 - <<'PY'
          import os, base64, pathlib, re, sys, binascii
          s=''.join(os.environ["P12_BASE64"].split()).strip('"').strip("'")
          if not re.fullmatch(r'[A-Za-z0-9+/=]+', s):
              sys.exit(2)
          s += "=" * ((4 - len(s) % 4) % 4)
          pathlib.Path("/tmp/signing/cert.p12").write_bytes(base64.b64decode(s, validate=True))
          PY

          # --- Provisioning: kann CMS-Base64, XML-Plist oder Rohtext sein ---
          python3 - <<'PY'
          import os, base64, pathlib, re, binascii
          raw = os.environ["MOBILEPROVISION_BASE64"]
          s   = ''.join(raw.split()).strip('"').strip("'")
          data = None
          if re.fullmatch(r'[A-Za-z0-9+/=]+', s or ""):
              try:
                  s += "=" * ((4 - len(s) % 4) % 4)
                  data = base64.b64decode(s, validate=True)
              except binascii.Error:
                  data = None
          if data is None:
              data = raw.encode("utf-8")
          pathlib.Path("/tmp/signing/profile.mobileprovision").write_bytes(data)
          PY

          /usr/bin/openssl pkcs12 -info -in /tmp/signing/cert.p12 -passin pass:"$P12_PASSWORD" -nodes -nokeys >/dev/null \
            || { echo "Ungültiges .p12 oder falsches Passwort"; exit 1; }

          keychain initialize
          keychain add-certificates --certificate /tmp/signing/cert.p12 --certificate-password "$P12_PASSWORD"

          PROV="/tmp/signing/profile.mobileprovision"
          [[ -s "$PROV" ]] || { echo "Provisioning-Profile leer"; exit 1; }

          PLIST="/tmp/signing/profile.plist"; rm -f "$PLIST"

          # 1) Versuche CMS -> Plist
          if /usr/bin/security cms -D -i "$PROV" -o "$PLIST" >/dev/null 2>&1 && [[ -s "$PLIST" ]]; then
            :
          else
            # 2) Falls Text mit eingebettetem <plist>, extrahiere nur den XML-Block
            if grep -a -q "<plist" "$PROV"; then
              awk 'f{print} /<plist/{f=1} /<\/plist>/{print; exit}' "$PROV" > "$PLIST" || true
              /usr/bin/plutil -convert xml1 "$PLIST" >/dev/null 2>&1 || true
            fi
            # 3) Fallback OpenSSL
            if [[ ! -s "$PLIST" ]] || ! /usr/bin/plutil -p "$PLIST" >/dev/null 2>&1; then
              if /usr/bin/openssl smime -inform DER -verify -noverify -in "$PROV" -out "$PLIST" >/dev/null 2>&1; then :
              elif /usr/bin/openssl smime -inform PEM -verify -noverify -in "$PROV" -out "$PLIST" >/dev/null 2>&1; then :
              fi
            fi
          fi

          # 4) Letzte Rettung per Python: <plist> Block isolieren und validieren
          python3 - <<'PY'
          import re, plistlib, pathlib
          prov=pathlib.Path("/tmp/signing/profile.mobileprovision")
          plist=pathlib.Path("/tmp/signing/profile.plist")
          try:
              if (not plist.exists()) or plist.stat().st_size==0:
                  try:
                      txt=prov.read_text(errors='ignore')
                  except Exception:
                      txt=None
                  if txt and "<plist" in txt:
                      m=re.search(r'<plist[\\s\\S]*</plist>', txt)
                      if m:
                          plist.write_text(m.group(0))
              # Validierung
              with plist.open('rb') as f:
                  plistlib.load(f)
          except Exception:
              pass
          PY

          # Prüfen
          if ! /usr/bin/plutil -p "$PLIST" >/dev/null 2>&1; then
            echo "Provisioning-Profile ungültig"; exit 1
          fi

          # UUID extrahieren
          UUID="$(
            /usr/bin/plutil -extract UUID raw -o - "$PLIST" 2>/dev/null \
            || /usr/libexec/PlistBuddy -c 'Print :UUID' "$PLIST" 2>/dev/null || true
          )"
          if [[ -z "$UUID" ]]; then
            UUID="$(python3 - <<'PY'
import plistlib
try:
    with open("/tmp/signing/profile.plist","rb") as f:
        d=plistlib.load(f)
    print(d.get("UUID",""))
except Exception:
    print("")
PY
)"
          fi
          [[ -n "$UUID" ]] || { echo "Profil ungültig: UUID nicht gefunden"; exit 1; }

          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp "$PROV" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
          cp "$PLIST" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.plist"

          xcode-project use-profiles

      - name: Build IPA
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          # Flutter vorbereiten
          if [[ -f pubspec.yaml ]]; then
            flutter --version
            flutter pub get
            flutter precache --ios
            flutter build ios --release --no-codesign
          fi

          # Pods
          if [[ -f ios/Podfile ]]; then
            gem list cocoapods -i >/dev/null 2>&1 || sudo gem install cocoapods --no-document

            # iOS-Deployment-Target auf 14.0 für google_maps_flutter_ios
            if grep -qE "^platform :ios" ios/Podfile; then
              sed -i.bak "s/^platform :ios.*/platform :ios, '14.0'/" ios/Podfile
            else
              sed -i.bak "1s;^;platform :ios, '14.0'\n;" ios/Podfile
            fi
            export IPHONEOS_DEPLOYMENT_TARGET=14.0

            (cd ios && pod repo update >/dev/null 2>&1 || true)
            (cd ios && pod install)
          fi

          # Workspace/Projekt erkennen
          WS="$(find ios -maxdepth 3 -name "*.xcworkspace" -print -quit 2>/dev/null || true)"
          [[ -n "$WS" ]] || WS="$(find . -path "./macos" -prune -o -name "*.xcworkspace" -print -quit || true)"
          PROJ=""
          if [[ -z "$WS" ]]; then
            PROJ="$(find ios -maxdepth 3 -name "*.xcodeproj" -print -quit 2>/dev/null || true)"
            [[ -n "$PROJ" ]] || PROJ="$(find . -path "./macos" -prune -o -name "*.xcodeproj" -print -quit || true)"
          fi
          [[ -n "$WS" || -n "$PROJ" ]] || { echo "Kein iOS .xcworkspace oder .xcodeproj gefunden"; exit 1; }

          # Schemes lesen
          LIST_JSON="$(/usr/bin/xcodebuild ${WS:+-workspace "$WS"} ${PROJ:+-project "$PROJ"} -list -json 2>/dev/null || true)"
          DETECTED="$(/usr/bin/python3 - <<'PY'
          import json,sys
          try:
            d=json.loads(sys.stdin.read() or "{}")
            s=d.get("workspace",{}).get("schemes") or d.get("project",{}).get("schemes") or []
            print("\n".join(s))
          except Exception:
            pass
          PY
          <<<"$LIST_JSON")"

          WANT="${SCHEME:-}"
          if [[ -n "$WANT" ]] && grep -Fxq "$WANT" <<<"$DETECTED"; then
            PICK="$WANT"
          elif grep -Fxq "Runner" <<<"$DETECTED"; then
            PICK="Runner"
          else
            PICK="$(head -n1 <<<"$DETECTED")"
          fi
          if [[ -z "${PICK:-}" ]]; then
            LIST_TXT="$(/usr/bin/xcodebuild ${WS:+-workspace "$WS"} ${PROJ:+-project "$PROJ"} -list 2>/dev/null || true)"
            PICK="$(awk '/Schemes:/{p=1;next} p && NF{print;exit}' <<<"$LIST_TXT" | sed 's/^[[:space:]]*//')"
          fi
          [[ -n "${PICK:-}" ]] || { echo "Kein Scheme gefunden"; /usr/bin/xcodebuild ${WS:+-workspace "$WS"} ${PROJ:+-project "$PROJ"} -list || true; exit 1; }
          SCHEME="$PICK"
          echo "Verwende Scheme: $SCHEME"

          # Schema validieren (+ ggf. auf Projekt fallen)
          set -o pipefail
          if [[ -n "$WS" ]]; then
            if ! xcodebuild -workspace "$WS" -scheme "$SCHEME" -showBuildSettings >/dev/null; then
              echo "Schema '$SCHEME' nicht im Workspace nutzbar. Versuche Projekt…"
              if [[ -n "$PROJ" ]] && xcodebuild -project "$PROJ" -scheme "$SCHEME" -showBuildSettings >/dev/null; then
                WS=""
                echo "Wechsle auf Projekt: $PROJ"
              else
                echo "Kein gültiges Scheme nutzbar."
                /usr/bin/xcodebuild ${WS:+-workspace "$WS"} ${PROJ:+-project "$PROJ"} -list || true
                exit 1
              fi
            fi
          else
            xcodebuild -project "$PROJ" -scheme "$SCHEME" -showBuildSettings >/dev/null
          fi

          # Archive
          CONFIGURATION="${CONFIGURATION:-Release}"
          DESTINATION="generic/platform=iOS"
          DATE_DIR="$(date +%Y-%m-%d)"
          TIME_TAG="$(date +%H-%M-%S)"
          ARCHIVE_DIR="$HOME/Library/Developer/Xcode/Archives/${DATE_DIR}"
          mkdir -p "$ARCHIVE_DIR"
          ARCHIVE_PATH="${ARCHIVE_DIR}/${SCHEME}-${TIME_TAG}.xcarchive"

          if [[ -n "$WS" ]]; then
            echo "Archive (workspace) -> $ARCHIVE_PATH"
            xcodebuild -workspace "$WS" -scheme "$SCHEME" -configuration "$CONFIGURATION" -destination "$DESTINATION" clean archive -archivePath "$ARCHIVE_PATH" CODE_SIGN_STYLE=Manual IPHONEOS_DEPLOYMENT_TARGET=14.0 | tee /tmp/xcodebuild_logs_archive.log
          else
            echo "Archive (project) -> $ARCHIVE_PATH"
            xcodebuild -project "$PROJ" -scheme "$SCHEME" -configuration "$CONFIGURATION" -destination "$DESTINATION" clean archive -archivePath "$ARCHIVE_PATH" CODE_SIGN_STYLE=Manual IPHONEOS_DEPLOYMENT_TARGET=14.0 | tee /tmp/xcodebuild_logs_archive.log
          fi

          # ExportOptions
          EXPORT_METHOD="${EXPORT_METHOD:-app-store}"
          EXPORT_PLIST="/tmp/ExportOptions.plist"
          cat > "$EXPORT_PLIST" <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>${EXPORT_METHOD}</string>
            <key>signingStyle</key><string>manual</string>
            <key>destination</key><string>export</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>uploadBitcode</key><false/>
          </dict></plist>
          PLIST

          # Export
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportPath "build/ios/ipa" -exportOptionsPlist "$EXPORT_PLIST" | tee /tmp/xcodebuild_logs_export.log
          echo "IPA unter build/ios/ipa"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs*.log
      - /tmp/xcodebuild_logs_*.log
      - $HOME/Library/Developer/Xcode/Archives/**/*
