workflows:
  ios_inline_signing:
    name: iOS Inline Signing
    environment:
      vars:
        # Hier deinen Workspace-Namen eintragen (falls du .xcworkspace hast)
        WORKSPACE: "App.xcworkspace"
        SCHEME: "App"
        EXPORT_METHOD: "app-store"   # app-store | development | ad-hoc | enterprise

        # ERSETZEN mit DEINEN Base64-Daten OHNE UMBRÜCHE!
        P12_BASE64: "HIER_DEIN_P12_BASE64_REIN" 
        MOBILEPROVISION_BASE64: "HIER_DEIN_PROVISION_BASE64_REIN"
        P12_PASSWORD: "HIER_DEIN_P12_PASSWORT"

    scripts:
      - name: Install signing (inline)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          # 0) Preflight
          [[ -n "${P12_BASE64:-}" ]] || { echo "P12_BASE64 leer"; exit 1; }
          [[ -n "${MOBILEPROVISION_BASE64:-}" ]] || { echo "MOBILEPROVISION_BASE64 leer"; exit 1; }
          [[ -n "${P12_PASSWORD:-}" ]] || { echo "P12_PASSWORD leer"; exit 1; }

          # 1) Decode mit Padding-Korrektur (python vermeidet base64 Fehler)
          mkdir -p /tmp/signing
          python3 - <<'PY'
          import os, base64, pathlib
          def b64_to_file(env, path):
              s = ''.join(os.environ[env].split())
              s += '=' * ((4 - len(s) % 4) % 4)
              pathlib.Path(path).write_bytes(base64.b64decode(s))
          b64_to_file('P12_BASE64', '/tmp/signing/cert.p12')
          b64_to_file('MOBILEPROVISION_BASE64', '/tmp/signing/profile.mobileprovision')
          PY

          # 2) Zertifikat prüfen
          if ! /usr/bin/openssl pkcs12 -info -in /tmp/signing/cert.p12 -passin pass:"$P12_PASSWORD" -nodes -nokeys >/dev/null 2>&1; then
            echo "Ungültiges .p12 oder falsches Passwort"; exit 1
          fi

          # 3) Keychain einrichten
          keychain initialize
          keychain add-certificates \
            --certificate /tmp/signing/cert.p12 \
            --certificate-password "$P12_PASSWORD"

          # 4) Profil mappen
          xcode-project use-profiles \
            --provisioning-profile /tmp/signing/profile.mobileprovision

      - name: Build IPA
        script: |
          set -euo pipefail
          DEST="-destination 'generic/platform=iOS'"
          if [[ -n "${WORKSPACE:-}" && -f "$WORKSPACE" ]]; then
            xcode-project build-ipa \
              --workspace "$WORKSPACE" \
              --scheme "$SCHEME" \
              --archive-flags="$DEST" \
              --export-method "$EXPORT_METHOD"
          else
            PROJ="${WORKSPACE%.xcworkspace}.xcodeproj"
            [[ -f "$PROJ" ]] || PROJ=$(ls *.xcodeproj | head -n1)
            xcode-project build-ipa \
              --project "$PROJ" \
              --scheme "$SCHEME" \
              --archive-flags="$DEST" \
              --export-method "$EXPORT_METHOD"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/Archives/**/*
