workflows:
  ios_release_upload:
    name: "iOS Release • Build + Upload"
    triggering:
      events:
        - manual
      cancel_previous_builds: true
    environment:
      vars:
        SCHEME: "Runner"
        EXPORT_METHOD: "app-store"
        # Signing
        P12_BASE64: "MIINGgIBAzCCDMgGCSqGSIb3DQEHAaCCDLkEggy1MIIMsTCCBuoGCSqGSIb3DQEHBqCCBtswggbXAgEAMIIG0AYJKoZIhvcNAQcBMF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBAdL1LKBpFSFOoFjkqIEDU7AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ6VZan2d5s5FcLkHKL9+55oCCBmAhTYG3xU19ISegrMlGJ9NfSHeLHKRy+z5cdNBOG0V9l0OZJfYCQf8AZlOZaUOxJX3k+o3l8t09+RZIhWHbklN3lKZjVCejRfDG2a1pieWH0D9Icp4/dCJgGdcTHpWQBX1cTOunLpcOHlKZ1FPCk6UsNYrOfTtzOyR6gOZzNPzrRv3WjQsgYuLSV9Oyz9/M2Aqul/R3O/G4AHQ/mVpl2nmKCDROpmoya2P3tNodsH/dYF2rS4s+mpVh1Cxhfqjo6r7CtMB/x7fKeB0vcIBxqTGmfyZPIMuCAcPEdR2uX501OtIF+jexZmlJbvol9PpuZH9yk3CUg1wm6+YP55RVStcZQdoSuUFBk4VFMnuonMBZp7CvFkJCS6yAwNB+fynFMOXYeD7Vx9lqXHr1w0ggII3VLp0jZDId42Ffm9QS7Pqx8x0g0RnGRZKXXbBJSVrtiAI6/AGZxKDwZJf/RYQsSZGMcFnni3qWPhtGBpyyb1+caY6dyMORCZY5FymsA1H5ggOIeUOkZfwyV8kkMvWNYtne8EGPZnvAhjuC+x8GfLudVryTz2mobZcCS7OcFbVZGoCXl7CTzAouAKUzhW6RGWO3HZMStHjrTjiX5dphbYZDQX6fOwjaBROjxkubHkh1Vy/KxNJ3ydJenJdkcoBSJec2fgMM0+puTD6hY0FqoUKWsO7J0KKLBQB3m62ru4DdOOtUh+S31nfo1SqClXHiHrtqXV8XOGFV0yqARV842Sqg6ZslWxtvxSRu8H6KTMdZ7VKhQyH9Mx23AU7uvxg1wRboa+QgGTFrGO6aIjbVzvC/IuqrYGmQMdFSDkIavTPsFSdJOfp/yhpr8NxFoz2iBU/vyWRJCULw4vH2iCEXq3wBp9YlxjIrfnJekf++BzFoTYkgdtQ1PduKB8r5GjOokTQWKXD3koNAoSurDctrSaIOyXasXqmMe4FmcCSoQSwUoC5w+r981FXfMaHAWqhjM+4/HPRN3yPzM5oI3Ffz9q58I5IG1oKdar7nuAF4ifSdR9GWixkPaW2Wb5xRKGiGKzd/S48MyvmPO2asCy39tt+HJUFM18uqlwVUCB+EOKMQYOe/+bjpIkIs9KOQxp/mKONX8ktaQ9v6gci+GXY77RuKe8Aszhlw3n+/LmtJVWyTPN0O6fYk87EMHoJY7jpNPsSxpi+Q/e5UWSa7seUgPhWKA2/bBAE2MRqM78KGgUQRbCNopJnQ8BWETx5G6q8m12uMFZnYX7gmEhT5q0+gn9Wx1mBYYk0rtgdEQpunUNn5KxwmzH6Km/w6j5ko1I3V0ul3+HTFlrfUFTf4HIZ1nUs1+/G24eZQY3COG4AKuTKUuQl0Rbdwt4sk+cJSlVdsxkfcV0BX1e6ZbZfmgLdcPu9+lByIcGT462rbSqoveVueSLZrRsIWEwPnMcx8zPUKCL3T4MqhVqGszWlI3OhJMNmttxNHuOnJSQwjGaEPYuEdYBoYQrW4iHx1SVHFJ6g05RIiZVSJNAQwiLVX+NXfrN5JQsgnBaxcu3ViDOa02StsOXph+yLHEEyfbaPKcwnzcFV8P0ZHu4/DXySDXBGf7MBFaYApHyk/rl68oYCQJ4iJOxFNrh29p4tdTWIQzicaZtVHrTuFHSIrzlzRbB/m/54GNIMqJCXI8QskhrMkPLjvRbqFAJDB9+J1v3F2ZE1RPfcljR6B24noW3WoyYl38Vzq34xJtIBcYub3e+6DHNTwX5LseBEaQz6DzPcLC2KccSJpJIKOHSF4A223eSTYReKSQWNKYuwckpfWeMKZswbn6TYfSGJno59bXAq1kaDWVgjGN0sYGhj0ZslxHH6KTIiK++nIy0OG980/agdsjGhopBfinP+yfg6k9cYpqhtSFPfnAe4ODNZS4j9pMRWLuTjOA045yX4w5v4ySzFHHPIJpoQZ5OGeBPGeszJbXvtyABxgH5wjOqMn5MEoO/G7pDRCqiALBhTQacVWFm6OIuAbeYA6xrHTjCV0Lt0Slw4vsCi5EdD5LcZHjwTZzK5LxsH1cpYUdqQJ0VcAKZzCTRQBGuXeAor0DHh93FQ7+kfFRQPCCBpuPchjQ2WbXPZ8NkiBSuv9TJP8AhtXaDBS1wXB54C1AVCTFRQgx7SGUrlav5YUKhDk1O5nezrbRwt/PebxOrc6AAdC+ZaXlQ9h2Va//k8wggW/BgkqhkiG9w0BBwGgggWwBIIFrDCCBagwggWkBgsqhkiG9w0BDAoBAqCCBTkwggU1MF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBDQSQXrUXhjOYjATYshh5P7AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQGmd4OUt1W+zZntQ2dDS4VwSCBNDnvTPYiAx9YcH/zQeW/K8IL0pRkJH5MFGDJ+sz5dOib66IO9Amw/cvAaLZ/YGpmRBEkSBENIi4EAYdZrtpyHVMonqG9x1qX6qF7hPg8QiNmcObBjacu0tsZDzxJRngqQaKOtl39WMBHTW15unPXRYnEYl6tSU3x7XSzHZ4NJ7p5R89o0pMIRpaSZHXbfrONCdQIbDiQwSSyGTZ42RAk20TVTH7V+ONsqPHOee17NdPxBEOsPaDwUY0NQkHEk+2MSbqmjd3cUXdoZXieyvjjj/ueXRzFnGcyCSCXEMT6U1p1vqhBAOa1/BPboGEX2kRMkPYuOoPmoDiA/Yrx+U0KF1iq3J9GgikHrGvRAnvyfgIW7Q8AguoriDQ1l5UPWdq2KWRk3HxGNBrRKtSqufq2fvYdqVN+ztysuQEWevDN7aaycdogK4zSoooWq6cw7L1kVWCvkO3EvZvkd5Kkff7807ZKqJQpNlan1AIsI6K+WLyi/yPE0u0PfFIO8lfojmuX8I9ahKDV5Y3Po3Pl1QpeeTXK76ZUMIvX/fDEAu4BGY1zgJ8Onuo5Ob6QasK7pF98dmAKpDfe4c9qRw/A3LgrDfNnmIfiLvFR84JkzwvGZxlkec51trygFJDt7SRwejMa9uzV2DIsdfvMkecPNLbsHJ4WIKPeduzPKJZyxOe/N4a9doX92ixzUGit/keYZr4Tb18URRPYbYOZixQUemEdDq03rMbM5PmDNIX0TLp03FbogwAaAXI5gO5DwQ+4YDGKpVlXesR57Imk3tcfWVttStRcDskCweVTeB5STkL7RBr6fzroxoYLe7C3B8GvDAfC5uWr7LFalxMd1s0bksrVFMamHEaOGb4w8M7K/e8aOYb6CHZUW0fj5g0HqUcOvP9Wf215pLRCtue7lwECS1939pEYv/64ejfR69ItXK0qm5A9BNhKDquYL1wFm5ddnPtxkFtaP8q4vpNlvKn4G0sl3o4kbd0VI+N5p8AYnEj0j9AZcOycctShYu11AtmUFK1hui3+kLkSZbz1M1Ub7/yJomIUSKxXwTxyrE9eM51EN5geWyGv2ZQ4Atd6HWlZTnAVHXCnHrXqrL14zDXSCh5xPC8DB3NB7RHjWmO6jf4IL+Op2zF7GhqOns42zJOuBDvMq7+XFIH9IHIwkgpohalGIlWrly+M2N+jtgCkj7gkUQlg/2C/YydrnLq9B8hWlrOytIizzAaQJz2uY4fitWnK8Ma7XMP/PyvjDq+9jDON52ECXJhfvEZ2J4RaxlET/HLP6NFxllbZX+CbkptNgFqbSCLIAuFJtN4swmmfc3I7pkZCHtYZt7JNOBZPtV6AcR8bnXv73kvOE4SdwcEUrL7rNSVTcnPpi8ywScT6J+rvS9JAJeViiFj49vefRF0VN9KlG/SqQP/04O6gl8NqlHMRcseoC4ivCXmlcKq/h1EWNwMc2z02JB+tXnuSU6eRykSqAznjYbxEFmIvoI1FZ2FYTPiS8P2LJCX+MCNZ0aJzUhRgqTssZG9EUwcX6VToSKTaRW1j82iPprni2lczcm6TjJWH81OQczQqcVYgHtaiD29gPpqGXc8ULrpcvtSop6lkdcMOjxPsMRqOeHhMDz1XDHaN3tifdVnXY5H96avdMdN/DFYMCMGCSqGSIb3DQEJFTEWBBSI9sO5FWCMYWfLfyxQB7eUZwqQ8zAxBgkqhkiG9w0BCRQxJB4iAFAAYQByAHQAeQBQAGkAbgBTAGkAZwBuAGEAdAB1AHIAZTBJMDEwDQYJYIZIAWUDBAIBBQAEIBVsIffB93ng+h5nbeyrXFyo3pIzErauD+kM0U6P9aCtBBBUAlQ0znxosKMKADrUdminAgIIAA=="              # Einzeilige Base64 der .p12
        P12_PASSWORD: "Yamahayz85"            # Passwort zur .p12
        MOBILEPROVISION_BASE64: ""  # Base64 ODER kompletter XML-Plist
        # App Store Connect API Key
        ASC_KEY_ID: ""              # z.B. ABCD123456
        ASC_ISSUER_ID: ""           # UUID
        ASC_PRIVATE_KEY: |          # Inhalt der .p8 (BEGIN/END lines inkl.)
          -----BEGIN PRIVATE KEY-----
          ...
          -----END PRIVATE KEY-----
    scripts:
      - name: "Install signing (inline)"
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          req(){ [[ -n "${!1:-}" ]] || { echo "$1 leer"; exit 1; }; }
          req P12_BASE64; req P12_PASSWORD; req MOBILEPROVISION_BASE64

          mkdir -p /tmp/signing

          # .p12 decodieren
          python3 - <<'PY'
          import os, base64, pathlib, re, sys
          s=os.environ["P12_BASE64"].strip().strip('"').strip("'")
          if not re.fullmatch(r'[A-Za-z0-9+/=]+', s): sys.exit(2)
          s += "=" * ((4 - len(s) % 4) % 4)
          pathlib.Path("/tmp/signing/cert.p12").write_bytes(base64.b64decode(s, validate=True))
          PY

          # Provisioning: Base64 oder Roh-XML
          python3 - <<'PY'
          import os, base64, pathlib, re, binascii
          raw=os.environ["MOBILEPROVISION_BASE64"]
          s=''.join(raw.split()).strip('"').strip("'")
          data=None
          if s and re.fullmatch(r'[A-Za-z0-9+/=]+', s):
              try:
                  s+= "="*((4-len(s)%4)%4)
                  data=base64.b64decode(s, validate=True)
              except binascii.Error:
                  data=None
          pathlib.Path("/tmp/signing/profile.mobileprovision").write_bytes(
              data if data is not None else raw.encode("utf-8"))
          PY

          # .p12 prüfen + importieren
          /usr/bin/openssl pkcs12 -info -in /tmp/signing/cert.p12 -passin pass:"$P12_PASSWORD" -nodes -nokeys >/dev/null \
            || { echo "Ungültiges .p12 oder Passwort"; exit 1; }
          keychain initialize
          keychain add-certificates --certificate /tmp/signing/cert.p12 --certificate-password "$P12_PASSWORD"

          PROV="/tmp/signing/profile.mobileprovision"
          [[ -s "$PROV" ]] || { echo "Provisioning-Profile leer"; exit 1; }

          # Plist extrahieren
          PLIST="/tmp/signing/profile.plist"; rm -f "$PLIST"
          /usr/bin/security cms -D -i "$PROV" -o "$PLIST" >/dev/null 2>&1 || true
          [[ -s "$PLIST" ]] || /usr/bin/openssl smime -inform DER -verify -noverify -in "$PROV" -out "$PLIST" >/dev/null 2>&1 || true
          [[ -s "$PLIST" ]] || awk 'f{print} /<plist/{f=1} /<\/plist>/{print; exit}' "$PROV" > "$PLIST" || true
          /usr/bin/plutil -convert xml1 "$PLIST" >/dev/null 2>&1 || true
          /usr/bin/plutil -p "$PLIST" >/dev/null 2>&1 || { echo "Provisioning-Profile ungültig"; exit 1; }

          UUID="$(python3 - <<'PY'
          import plistlib; d=plistlib.load(open("/tmp/signing/profile.plist","rb"))
          print(d.get("UUID",""))
          PY
          )"
          [[ -n "$UUID" ]] || { echo "Profil-UUID fehlt"; exit 1; }

          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp "$PROV"  "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
          cp "$PLIST" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.plist"

          xcode-project use-profiles

      - name: "Build iOS (.xcarchive)"
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          export IPHONEOS_DEPLOYMENT_TARGET=14.0

          # Flutter vorbereiten
          if [[ -f pubspec.yaml ]]; then
            flutter --version
            flutter pub get
            flutter precache --ios
            flutter build ios --release --no-codesign
          fi

          # Pods sicherstellen
          if [[ -d ios ]]; then
            gem list cocoapods -i >/dev/null 2>&1 || sudo gem install cocoapods --no-document
            (cd ios && pod repo update >/dev/null 2>&1 || true)
            (cd ios && pod install)
          fi

          # Workspace/Projekt finden
          WS="$(find ios -maxdepth 3 -name "*.xcworkspace" -print -quit 2>/dev/null || true)"
          [[ -n "$WS" ]] || WS="$(find . -path "./macos" -prune -o -name "*.xcworkspace" -print -quit || true)"
          PROJ=""
          if [[ -z "$WS" ]]; then
            PROJ="$(find ios -maxdepth 3 -name "*.xcodeproj" -print -quit 2>/dev/null || true)"
            [[ -n "$PROJ" ]] || PROJ="$(find . -path "./macos" -prune -o -name "*.xcodeproj" -print -quit || true)"
          fi
          [[ -n "$WS" || -n "$PROJ" ]] || { echo "Kein Xcode-Projekt gefunden"; exit 1; }

          # Scheme bestimmen
          LIST_JSON_FILE="$(mktemp)"
          /usr/bin/xcodebuild ${WS:+-workspace "$WS"} ${PROJ:+-project "$PROJ"} -list -json >"$LIST_JSON_FILE" 2>/dev/null || true
          SCHEME="$(LIST_JSON_PATH="$LIST_JSON_FILE" python3 - <<'PY'
import json, os
p=os.environ.get("LIST_JSON_PATH","")
try: d=json.loads(open(p).read())
except: d={}
s=(d.get("workspace",{}) or {}).get("schemes") or (d.get("project",{}) or {}).get("schemes") or []
print("Runner" if "Runner" in s else (s[0] if s else ""))
PY
          )"
          [[ -n "$SCHEME" ]] || { echo "Kein Scheme"; exit 1; }
          echo "Scheme: $SCHEME"

          CONFIGURATION="${CONFIGURATION:-Release}"
          DESTINATION="generic/platform=iOS"
          DATE_DIR="$(date +%Y-%m-%d)"
          TIME_TAG="$(date +%H-%M-%S)"
          ARCHIVE_DIR="$HOME/Library/Developer/Xcode/Archives/${DATE_DIR}"
          mkdir -p "$ARCHIVE_DIR"
          ARCHIVE_PATH="${ARCHIVE_DIR}/${SCHEME}-${TIME_TAG}.xcarchive"

          if [[ -n "$WS" ]]; then
            xcodebuild -workspace "$WS" -scheme "$SCHEME" -configuration "$CONFIGURATION" -destination "$DESTINATION" clean archive -archivePath "$ARCHIVE_PATH" CODE_SIGN_STYLE=Manual IPHONEOS_DEPLOYMENT_TARGET=14.0 | tee /tmp/xcodebuild_logs_archive.log
          else
            xcodebuild -project "$PROJ" -scheme "$SCHEME" -configuration "$CONFIGURATION" -destination "$DESTINATION" clean archive -archivePath "$ARCHIVE_PATH" CODE_SIGN_STYLE=Manual IPHONEOS_DEPLOYMENT_TARGET=14.0 | tee /tmp/xcodebuild_logs_archive.log
          fi

          echo "ARCHIVE_PATH=$ARCHIVE_PATH" | tee -a $CM_ENV

      - name: "Export IPA"
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          : "${ARCHIVE_PATH:?ARCHIVE_PATH fehlt}"
          EXPORT_METHOD="${EXPORT_METHOD:-app-store}"
          EXPORT_PLIST="/tmp/ExportOptions.plist"
          cat > "$EXPORT_PLIST" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>method</key><string>__METHOD__</string>
  <key>signingStyle</key><string>manual</string>
  <key>destination</key><string>export</string>
  <key>stripSwiftSymbols</key><true/>
  <key>compileBitcode</key><false/>
  <key>uploadBitcode</key><false/>
</dict></plist>
PLIST
          sed -i.bak "s/__METHOD__/${EXPORT_METHOD}/" "$EXPORT_PLIST"

          mkdir -p build/ios/ipa
          xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportPath "build/ios/ipa" -exportOptionsPlist "$EXPORT_PLIST" | tee /tmp/xcodebuild_logs_export.log
          echo "IPA_DIR=$(pwd)/build/ios/ipa" | tee -a $CM_ENV
          ls -lh build/ios/ipa || true

    artifacts:
      - "build/ios/ipa/*.ipa"
      - "/tmp/xcodebuild_logs*.log"
      - "$HOME/Library/Developer/Xcode/Archives/**/*"

    publishing:
      app_store_connect:
        api_key:
          key_id: "$ASC_KEY_ID"
          issuer_id: "$ASC_ISSUER_ID"
          private_key: "$ASC_PRIVATE_KEY"
        submit_to_testflight: true
        # Optional:
        # beta_groups:
        #   - "External Testers"
        # release_type: "MANUAL"
