workflows:
  ios_inline_signing:
    name: iOS Inline Signing (nur YAML)
    environment:
      vars:
        WORKSPACE: "App.xcworkspace"      # ggf. leeren, wenn .xcodeproj
        SCHEME: "App"
        EXPORT_METHOD: "app-store"         # app-store | ad-hoc | development | enterprise

        # ↓↓↓ ERSETZEN: Base64-Inhalte direkt hier einfügen
        P12_BASE64: |
          PASTE_DEIN_P12_ALS_BASE64_HIER_REIN
        MOBILEPROVISION_BASE64: |
          PASTE_DEIN_MOBILEPROVISION_ALS_BASE64_HIER_REIN
        P12_PASSWORD: "DEIN_P12_PASSWORT"

    scripts:
      - name: Preflight
        script: |
          set -euo pipefail
          [[ -n "${P12_BASE64// }" ]] || { echo "P12_BASE64 leer"; exit 1; }
          [[ -n "${MOBILEPROVISION_BASE64// }" ]] || { echo "MOBILEPROVISION_BASE64 leer"; exit 1; }
          [[ -n "${P12_PASSWORD:-}" ]] || { echo "P12_PASSWORD leer"; exit 1; }
          echo "Variablen vorhanden. Fahre fort."

      - name: Install signing (inline)
        script: |
          set -euo pipefail
          mkdir -p /tmp/signing
          echo "$P12_BASE64" | base64 -d > /tmp/signing/cert.p12
          echo "$MOBILEPROVISION_BASE64" | base64 -d > /tmp/signing/profile.mobileprovision

          keychain initialize
          keychain add-certificates \
            --certificate /tmp/signing/cert.p12 \
            --certificate-password "$P12_PASSWORD"

          xcode-project use-profiles \
            --provisioning-profile /tmp/signing/profile.mobileprovision

      - name: Build IPA
        script: |
          set -euo pipefail
          DEST="-destination 'generic/platform=iOS'"
          if [[ -n "${WORKSPACE:-}" && -f "$WORKSPACE" ]]; then
            xcode-project build-ipa \
              --workspace "$WORKSPACE" \
              --scheme "$SCHEME" \
              --archive-flags="$DEST" \
              --export-method "$EXPORT_METHOD"
          else
            PROJ="${WORKSPACE%.xcworkspace}.xcodeproj"
            [[ -f "$PROJ" ]] || PROJ=$(ls *.xcodeproj | head -n1)
            xcode-project build-ipa \
              --project "$PROJ" \
              --scheme "$SCHEME" \
              --archive-flags="$DEST" \
              --export-method "$EXPORT_METHOD"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/Archives/**/*
