workflows:
  ios:
    name: iOS
    environment:
      groups:
        - ios_credentials   # enthält: CM_CERTIFICATE (File), CM_CERTIFICATE_PASSWORD (Secure String), CM_PROVISIONING_PROFILE (File)
      vars:
        WORKSPACE: "App.xcworkspace"   # oder leer lassen, wenn du .xcodeproj nutzt
        SCHEME: "App"
        BUNDLE_ID: "com.example.app"
        EXPORT_METHOD: "app-store"      # app-store | ad-hoc | development | enterprise

    scripts:
      - name: Install signing
        script: |
          set -euo pipefail
          [[ -f "$CM_CERTIFICATE" ]] || { echo "CM_CERTIFICATE fehlt"; exit 1; }
          [[ -f "$CM_PROVISIONING_PROFILE" ]] || { echo "CM_PROVISIONING_PROFILE fehlt"; exit 1; }
          [[ -n "${CM_CERTIFICATE_PASSWORD:-}" ]] || { echo "CM_CERTIFICATE_PASSWORD leer"; exit 1; }

          keychain initialize
          keychain add-certificates \
            --certificate "$CM_CERTIFICATE" \
            --certificate-password "$CM_CERTIFICATE_PASSWORD"

          xcode-project use-profiles \
            --provisioning-profile "$CM_PROVISIONING_PROFILE"

      - name: Build IPA
        script: |
          set -euo pipefail
          DEST="-destination 'generic/platform=iOS'"
          if [[ -n "${WORKSPACE:-}" && -f "$WORKSPACE" ]]; then
            xcode-project build-ipa \
              --workspace "$WORKSPACE" \
              --scheme "$SCHEME" \
              --archive-flags="$DEST" \
              --export-method "$EXPORT_METHOD"
          else
            PROJ="${WORKSPACE%.xcworkspace}.xcodeproj"
            [[ -f "$PROJ" ]] || PROJ=$(ls *.xcodeproj | head -n1)
            xcode-project build-ipa \
              --project "$PROJ" \
              --scheme "$SCHEME" \
              --archive-flags="$DEST" \
              --export-method "$EXPORT_METHOD"
          fi

      - name: Sanity check (optional)
        script: |
          set -euo pipefail
          security find-identity -v -p codesigning || true
          xcode-project detect-signing || true

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/Archives/**/*

    publishing:
      email:
        recipients:
          - dev@example.com
        notify:
          success: true
          failure: true
