workflows:
  ios_release:
    name: iOS Release (TestFlight)
    integrations:
      app_store_connect: PartyPin

    environment:
      flutter: stable
      xcode: latest
      vars:
        CM_EXPORT_METHOD: app-store

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: Use signing (uploaded p12 + mobileprovision)
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: flutter build ipa --release --build-number ${CM_BUILD_ID}

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
