// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfIJDHRjDlEmPWpdO8bVhaMnVzBCkFYXI',
    appId: '1:777410329158:web:5b8ca9dd8358b97a012847',
    messagingSenderId: '777410329158',
    projectId: 'partypin-5dc3f',
    authDomain: 'partypin-5dc3f.firebaseapp.com',
    storageBucket: 'partypin-5dc3f.firebasestorage.app',
    measurementId: 'G-VWW2LHEDVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0NFsz40YdJrjQYf4-_FnNKU8yRIiiP0k',
    appId: '1:777410329158:android:86b661c1b32b3cd0012847',
    messagingSenderId: '777410329158',
    projectId: 'partypin-5dc3f',
    storageBucket: 'partypin-5dc3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGcuGxbH6Gm0lGAGNmB97NSaw8D3DXRpc',
    appId: '1:777410329158:ios:f64218076b29e31f012847',
    messagingSenderId: '777410329158',
    projectId: 'partypin-5dc3f',
    storageBucket: 'partypin-5dc3f.firebasestorage.app',
    iosBundleId: 'com.partypin.partyPin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGcuGxbH6Gm0lGAGNmB97NSaw8D3DXRpc',
    appId: '1:777410329158:ios:f64218076b29e31f012847',
    messagingSenderId: '777410329158',
    projectId: 'partypin-5dc3f',
    storageBucket: 'partypin-5dc3f.firebasestorage.app',
    iosBundleId: 'com.partypin.partyPin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfIJDHRjDlEmPWpdO8bVhaMnVzBCkFYXI',
    appId: '1:777410329158:web:5b512101bce70e17012847',
    messagingSenderId: '777410329158',
    projectId: 'partypin-5dc3f',
    authDomain: 'partypin-5dc3f.firebaseapp.com',
    storageBucket: 'partypin-5dc3f.firebasestorage.app',
    measurementId: 'G-C44QY0PBSC',
  );

}